@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.1\common\bin\cspybat" -f "D:\SVN_KOREA\가전-국내\1_가전 Touch Base Code\32_Bit\A31T21x\Base_Code\Release\Ver_1.20\Full_SRC  (Touch&UL&Gesture)\STKS_A31T216_Touch_Lib_Src_VER106_debug\example\touch\iar\settings\A31T216.Release.general.xcl" --backend -f "D:\SVN_KOREA\가전-국내\1_가전 Touch Base Code\32_Bit\A31T21x\Base_Code\Release\Ver_1.20\Full_SRC  (Touch&UL&Gesture)\STKS_A31T216_Touch_Lib_Src_VER106_debug\example\touch\iar\settings\A31T216.Release.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.1\common\bin\cspybat" -f "D:\SVN_KOREA\가전-국내\1_가전 Touch Base Code\32_Bit\A31T21x\Base_Code\Release\Ver_1.20\Full_SRC  (Touch&UL&Gesture)\STKS_A31T216_Touch_Lib_Src_VER106_debug\example\touch\iar\settings\A31T216.Release.general.xcl" "--debug_file=%~1" --backend -f "D:\SVN_KOREA\가전-국내\1_가전 Touch Base Code\32_Bit\A31T21x\Base_Code\Release\Ver_1.20\Full_SRC  (Touch&UL&Gesture)\STKS_A31T216_Touch_Lib_Src_VER106_debug\example\touch\iar\settings\A31T216.Release.driver.xcl" 

@echo off 
:end