/**
 *******************************************************************************
 * @file        touch_config.h
 * @author      ABOV R&D Division
 * @brief       A31T21x Touch setting configure header
 *
 * Copyright 2017 ABOV Semiconductor Co.,Ltd. All rights reserved.
 *
 * This file is licensed under terms that are found in the LICENSE file
 * located at Document directory.
 * If this file is delivered or shared without applicable license terms,
 * the terms of the BSD-3-Clause license shall be applied.
 * Reference: https://opensource.org/licenses/BSD-3-Clause
 ******************************************************************************/


#ifndef _TOUCH_CONFIG_H_
#define _TOUCH_CONFIG_H_

#include "touch_lib.h"

/*************************
    TOUCH CH
*************************/
#if 1
/* STKS Touch-A Board - Key */
#define CS00_USE    0   
#define CS01_USE    1   
#define CS02_USE    0   
#define CS03_USE    0   
#define CS04_USE    1   
#define CS05_USE    0   
#define CS06_USE    0   
#define CS07_USE    1   
#define CS08_USE    0   
#define CS09_USE    0   
#define CS10_USE    1   
#define CS11_USE    0   
#define CS12_USE    0   
#define CS13_USE    1   
#define CS14_USE    0   
#define CS15_USE    0   
#define CS16_USE    1   
#define CS17_USE    0   
#define CS18_USE    0   
#define CS19_USE    1   
#define CS20_USE    0
#define CS21_USE    0   
#define CS22_USE    0   // not use
#define CS23_USE    0   
#else
/* STKS Touch-B Board - Wheel & Slide */
#define CS00_USE    1   /* Slide CH0 */
#define CS01_USE    1   /* Slide CH1 */
#define CS02_USE    1   /* Slide CH2 */
#define CS04_USE    1   /* Slide CH3 */
#define CS03_USE    1   /* Slide CH4 */
#define CS05_USE    1   /* Slide CH5 */
#define CS06_USE    1   /* Slide CH6 */
#define CS07_USE    1   /* Slide CH7 */
#define CS08_USE    1   /* Wheel CH0 */
#define CS09_USE    1   /* Wheel CH7 */
#define CS10_USE    1   /* Wheel CH6 */
#define CS11_USE    1   /* Wheel CH5 */
#define CS12_USE    1   /* Wheel CH1 */
#define CS13_USE    1   /* Wheel CH2 */
#define CS14_USE    1   /* Wheel CH3 */
#define CS15_USE    1   /* Wheel CH4 */
#define CS16_USE    0   
#define CS17_USE    0   
#define CS18_USE    0   
#define CS19_USE    0   
#define CS20_USE    0
#define CS21_USE    0   
#define CS22_USE    0   
#define CS23_USE    0   
#endif

/************************************************************** don't modify *************************************************************/
#define ACT_KEY_NUM         (CS00_USE+CS01_USE+CS02_USE+CS03_USE+CS04_USE+CS05_USE+CS06_USE+CS07_USE+CS08_USE+CS09_USE+ \
                            CS10_USE+CS11_USE+CS12_USE+CS13_USE+CS14_USE+CS15_USE+CS16_USE+CS17_USE+CS18_USE+CS19_USE+ \
                            CS20_USE+CS21_USE+CS22_USE+CS23_USE)

#define ACT_KEY_BIT_VAL     (((uint32_t)CS00_USE<<0)  | ((uint32_t)CS01_USE<<1)  | ((uint32_t)CS02_USE<<2)  | ((uint32_t)CS03_USE<<3)  | ((uint32_t)CS04_USE<<4)  | \
                            ((uint32_t)CS05_USE<<5)  | ((uint32_t)CS06_USE<<6)  | ((uint32_t)CS07_USE<<7)  | ((uint32_t)CS08_USE<<8)  | ((uint32_t)CS09_USE<<9)  | \
                            ((uint32_t)CS10_USE<<10) | ((uint32_t)CS11_USE<<11) | ((uint32_t)CS12_USE<<12) | ((uint32_t)CS13_USE<<13) | ((uint32_t)CS14_USE<<14) | \
                            ((uint32_t)CS15_USE<<15) | ((uint32_t)CS16_USE<<16) | ((uint32_t)CS17_USE<<17) | ((uint32_t)CS18_USE<<18) | ((uint32_t)CS19_USE<<19) | \
                            ((uint32_t)CS20_USE<<20) | ((uint32_t)CS21_USE<<21) | ((uint32_t)CS22_USE<<22) | ((uint32_t)CS23_USE<<23) )

/****************************************************************************************************************************************/

#define MESH_SHIELD_EN      1

#define CH_SHIELD_EN        1

#define CH_SHIELD_CS00      0
#define CH_SHIELD_CS01      1
#define CH_SHIELD_CS02      0
#define CH_SHIELD_CS03      0
#define CH_SHIELD_CS04      1
#define CH_SHIELD_CS05      0
#define CH_SHIELD_CS06      0
#define CH_SHIELD_CS07      1
#define CH_SHIELD_CS08      0
#define CH_SHIELD_CS09      0
#define CH_SHIELD_CS10      1
#define CH_SHIELD_CS11      0
#define CH_SHIELD_CS12      0
#define CH_SHIELD_CS13      1
#define CH_SHIELD_CS14      0
#define CH_SHIELD_CS15      0
#define CH_SHIELD_CS16      1
#define CH_SHIELD_CS17      0
#define CH_SHIELD_CS18      0
#define CH_SHIELD_CS19      1
#define CH_SHIELD_CS20      0
#define CH_SHIELD_CS21      0
#define CH_SHIELD_CS22      0       
#define CH_SHIELD_CS23      0

#define CH_SHIELD_BIT_VAL   (((uint32_t)CH_SHIELD_CS00<<0)  | ((uint32_t)CH_SHIELD_CS01<<1) | ((uint32_t)CH_SHIELD_CS02<<2)  | ((uint32_t)CH_SHIELD_CS03<<3)  | ((uint32_t)CH_SHIELD_CS04<<4)  | \
                            ((uint32_t)CH_SHIELD_CS05<<5)  | ((uint32_t)CH_SHIELD_CS06<<6)  | ((uint32_t)CH_SHIELD_CS07<<7)  | ((uint32_t)CH_SHIELD_CS08<<8)  | ((uint32_t)CH_SHIELD_CS09<<9)  | \
                            ((uint32_t)CH_SHIELD_CS10<<10) | ((uint32_t)CH_SHIELD_CS11<<11) | ((uint32_t)CH_SHIELD_CS12<<12) | ((uint32_t)CH_SHIELD_CS13<<13) | ((uint32_t)CH_SHIELD_CS14<<14) | \
                            ((uint32_t)CH_SHIELD_CS15<<15) | ((uint32_t)CH_SHIELD_CS16<<16) | ((uint32_t)CH_SHIELD_CS17<<17) | ((uint32_t)CH_SHIELD_CS18<<18) | ((uint32_t)CH_SHIELD_CS19<<19) | \
                            ((uint32_t)CH_SHIELD_CS20<<20) | ((uint32_t)CH_SHIELD_CS21<<21) | ((uint32_t)CH_SHIELD_CS22<<22) | ((uint32_t)CH_SHIELD_CS23<<23) )

/****************************************************************************************************************************************/


/*************************
    REF CH
*************************/
/* Set ref H/W pin 'CS00' ~ 'CS23', if set 'CS_NONE', ref function disable*/
#define REF_CH_EN               0
#define REF_CH_BIT_VAL          CS02
#define REF_CH_SUM_CNT_VAL      8
#define REF_CH_LPF_C_VAL        INTENAL_CAPACITOR_5_6pF
#define REF_CH_LPF_R_VAL        SERIAL_REGISTER_100K


/******************************* Touch common parameter **********************************************/
#define TOUCH_CLK_VAL                   TOUCH_FREQ_4M
#define TOUCH_CLK_OFFSET_VAL            4                   /* Set 0x00 ~ 0x3F */
#define TOUCH_MODE_VAL                  TS_MODE_NORMAL      
#define TOUCH_PORT_SEL_VAL              MODE_OUT_LOW      
#define TOUCH_VHS_VAL                   4200                /* Set 3000 ~ 5000 */
#define TOUCH_COMP_REFV_VAL             3840                /* Set 2700 ~ 4500 */ /*Hisense mode 3700, normal mode 3840*/
#define TIMER_STARTUP_VAL               300                 /* Set 100ms ~ 1000ms */
#define TIMER_BASE_SAMPLE_VAL           500                 /* Set 100ms ~ 1000ms */
#define TIMER_BASE_REVERSE_SAMPLE_VAL   100                 /* Set 100ms ~ 500ms */
#define BASE_RELEASE_HOLD_CNT_VAL       3


/******************************* Touch channel parameter **********************************************/

#if 1      
/* STKS Touch-A Board - Key */
#define TOUCH_SUM_CNT_CH00      8       
#define TOUCH_SUM_CNT_CH01      8       
#define TOUCH_SUM_CNT_CH02      8       
#define TOUCH_SUM_CNT_CH03      8       
#define TOUCH_SUM_CNT_CH04      8       
#define TOUCH_SUM_CNT_CH05      8       
#define TOUCH_SUM_CNT_CH06      8       
#define TOUCH_SUM_CNT_CH07      8       
#define TOUCH_SUM_CNT_CH08      8       
#define TOUCH_SUM_CNT_CH09      8       
#define TOUCH_SUM_CNT_CH10      8       
#define TOUCH_SUM_CNT_CH11      8       
#define TOUCH_SUM_CNT_CH12      8       
#define TOUCH_SUM_CNT_CH13      8       
#define TOUCH_SUM_CNT_CH14      8       
#define TOUCH_SUM_CNT_CH15      8       
#define TOUCH_SUM_CNT_CH16      8
#define TOUCH_SUM_CNT_CH17      8
#define TOUCH_SUM_CNT_CH18      8
#define TOUCH_SUM_CNT_CH19      8
#define TOUCH_SUM_CNT_CH20      8
#define TOUCH_SUM_CNT_CH21      8
#define TOUCH_SUM_CNT_CH22      8
#define TOUCH_SUM_CNT_CH23      8

#else
/* STKS Touch-B Board - Wheel & Slide */
#define TOUCH_SUM_CNT_CH00      7       /* Slide CH0 */
#define TOUCH_SUM_CNT_CH01      7       /* Slide CH1 */
#define TOUCH_SUM_CNT_CH02      7       /* Slide CH2 */
#define TOUCH_SUM_CNT_CH03      7       /* Slide CH3 */
#define TOUCH_SUM_CNT_CH04      12      /* Slide CH4 */
#define TOUCH_SUM_CNT_CH05      12      /* Slide CH5 */
#define TOUCH_SUM_CNT_CH06      12      /* Slide CH6 */
#define TOUCH_SUM_CNT_CH07      8       /* Slide CH7 */
#define TOUCH_SUM_CNT_CH08      6       /* Wheel CH0 */
#define TOUCH_SUM_CNT_CH09      6       /* Wheel CH7 */
#define TOUCH_SUM_CNT_CH10      6       /* Wheel CH6 */
#define TOUCH_SUM_CNT_CH11      9       /* Wheel CH5 */
#define TOUCH_SUM_CNT_CH12      7       /* Wheel CH1 */
#define TOUCH_SUM_CNT_CH13      7       /* Wheel CH2 */
#define TOUCH_SUM_CNT_CH14      9       /* Wheel CH3 */
#define TOUCH_SUM_CNT_CH15      9       /* Wheel CH4 */
#define TOUCH_SUM_CNT_CH16      8
#define TOUCH_SUM_CNT_CH17      8
#define TOUCH_SUM_CNT_CH18      8
#define TOUCH_SUM_CNT_CH19      8
#define TOUCH_SUM_CNT_CH20      8
#define TOUCH_SUM_CNT_CH21      8
#define TOUCH_SUM_CNT_CH22      8
#define TOUCH_SUM_CNT_CH23      8
#endif

#define TOUCH_LPF_C_CH00        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH01        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH02        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH03        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH05        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH04        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH06        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH07        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH08        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH09        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH10        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH11        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH12        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH13        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH14        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH15        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH16        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH17        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH18        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH19        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH20        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH22        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH21        INTENAL_CAPACITOR_5_6pF
#define TOUCH_LPF_C_CH23        INTENAL_CAPACITOR_5_6pF

#define TOUCH_LPF_R_CH00        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH01        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH02        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH03        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH05        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH04        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH06        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH07        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH08        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH09        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH10        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH11        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH12        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH13        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH14        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH15        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH16        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH17        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH18        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH19        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH20        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH22        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH21        SERIAL_REGISTER_100K
#define TOUCH_LPF_R_CH23        SERIAL_REGISTER_100K

#define THD_DETECT_CH00         255
#define THD_DETECT_CH01         165
#define THD_DETECT_CH02         250
#define THD_DETECT_CH03         260
#define THD_DETECT_CH04         150
#define THD_DETECT_CH05         165
#define THD_DETECT_CH06         110
#define THD_DETECT_CH07         100
#define THD_DETECT_CH08         100
#define THD_DETECT_CH09         100
#define THD_DETECT_CH10         100
#define THD_DETECT_CH11         100
#define THD_DETECT_CH12         100
#define THD_DETECT_CH13         100
#define THD_DETECT_CH14         100
#define THD_DETECT_CH15         100
#define THD_DETECT_CH16         100
#define THD_DETECT_CH17         100
#define THD_DETECT_CH18         100
#define THD_DETECT_CH19         100
#define THD_DETECT_CH20         100
#define THD_DETECT_CH21         100
#define THD_DETECT_CH22         100
#define THD_DETECT_CH23         100

#define THD_RELEASE_RATE_CH00   70
#define THD_RELEASE_RATE_CH01   70
#define THD_RELEASE_RATE_CH02   70
#define THD_RELEASE_RATE_CH03   70
#define THD_RELEASE_RATE_CH04   70
#define THD_RELEASE_RATE_CH05   70
#define THD_RELEASE_RATE_CH06   70
#define THD_RELEASE_RATE_CH07   70
#define THD_RELEASE_RATE_CH08   70
#define THD_RELEASE_RATE_CH09   70
#define THD_RELEASE_RATE_CH10   70
#define THD_RELEASE_RATE_CH11   70
#define THD_RELEASE_RATE_CH12   70
#define THD_RELEASE_RATE_CH13   70
#define THD_RELEASE_RATE_CH14   70
#define THD_RELEASE_RATE_CH15   70
#define THD_RELEASE_RATE_CH16   70
#define THD_RELEASE_RATE_CH17   70
#define THD_RELEASE_RATE_CH18   70
#define THD_RELEASE_RATE_CH19   70
#define THD_RELEASE_RATE_CH90   70
#define THD_RELEASE_RATE_CH20   70
#define THD_RELEASE_RATE_CH21   70
#define THD_RELEASE_RATE_CH22   70
#define THD_RELEASE_RATE_CH23   70

#define THD_REVERSE_RATE_CH00   50
#define THD_REVERSE_RATE_CH01   50
#define THD_REVERSE_RATE_CH02   50
#define THD_REVERSE_RATE_CH03   50
#define THD_REVERSE_RATE_CH04   50
#define THD_REVERSE_RATE_CH05   50
#define THD_REVERSE_RATE_CH06   50
#define THD_REVERSE_RATE_CH07   50
#define THD_REVERSE_RATE_CH08   50
#define THD_REVERSE_RATE_CH09   50
#define THD_REVERSE_RATE_CH10   50
#define THD_REVERSE_RATE_CH11   50
#define THD_REVERSE_RATE_CH12   50
#define THD_REVERSE_RATE_CH13   50
#define THD_REVERSE_RATE_CH14   50
#define THD_REVERSE_RATE_CH15   50
#define THD_REVERSE_RATE_CH16   50
#define THD_REVERSE_RATE_CH17   50
#define THD_REVERSE_RATE_CH18   50
#define THD_REVERSE_RATE_CH19   50
#define THD_REVERSE_RATE_CH20   50
#define THD_REVERSE_RATE_CH21   50
#define THD_REVERSE_RATE_CH22   50
#define THD_REVERSE_RATE_CH23   50

#define BASE_TRACE_SPEED_CHECK_RATE_CH00    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH01    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH02    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH03    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH04    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH05    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH06    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH07    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH08    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH09    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH10    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH11    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH12    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH13    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH14    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH15    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH16    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH17    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH18    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH19    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH20    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH21    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH22    30
#define BASE_TRACE_SPEED_CHECK_RATE_CH23    30

#define BASE_TRACE_FAST_SPEED_CH00      1
#define BASE_TRACE_FAST_SPEED_CH01      1
#define BASE_TRACE_FAST_SPEED_CH02      1
#define BASE_TRACE_FAST_SPEED_CH03      1
#define BASE_TRACE_FAST_SPEED_CH04      1
#define BASE_TRACE_FAST_SPEED_CH05      1
#define BASE_TRACE_FAST_SPEED_CH06      1
#define BASE_TRACE_FAST_SPEED_CH07      1
#define BASE_TRACE_FAST_SPEED_CH08      1
#define BASE_TRACE_FAST_SPEED_CH09      1
#define BASE_TRACE_FAST_SPEED_CH10      1
#define BASE_TRACE_FAST_SPEED_CH11      1
#define BASE_TRACE_FAST_SPEED_CH12      1
#define BASE_TRACE_FAST_SPEED_CH13      1
#define BASE_TRACE_FAST_SPEED_CH14      1
#define BASE_TRACE_FAST_SPEED_CH15      1
#define BASE_TRACE_FAST_SPEED_CH16      1
#define BASE_TRACE_FAST_SPEED_CH17      1
#define BASE_TRACE_FAST_SPEED_CH18      1
#define BASE_TRACE_FAST_SPEED_CH19      1
#define BASE_TRACE_FAST_SPEED_CH20      1
#define BASE_TRACE_FAST_SPEED_CH21      1
#define BASE_TRACE_FAST_SPEED_CH22      1
#define BASE_TRACE_FAST_SPEED_CH23      1

#define BASE_TRACE_SLOW_SPEED_CH00      20
#define BASE_TRACE_SLOW_SPEED_CH01      20
#define BASE_TRACE_SLOW_SPEED_CH02      20
#define BASE_TRACE_SLOW_SPEED_CH03      20
#define BASE_TRACE_SLOW_SPEED_CH04      20
#define BASE_TRACE_SLOW_SPEED_CH05      20
#define BASE_TRACE_SLOW_SPEED_CH06      20
#define BASE_TRACE_SLOW_SPEED_CH07      20
#define BASE_TRACE_SLOW_SPEED_CH08      20
#define BASE_TRACE_SLOW_SPEED_CH09      20
#define BASE_TRACE_SLOW_SPEED_CH10      20
#define BASE_TRACE_SLOW_SPEED_CH11      20
#define BASE_TRACE_SLOW_SPEED_CH12      20
#define BASE_TRACE_SLOW_SPEED_CH13      20
#define BASE_TRACE_SLOW_SPEED_CH14      20
#define BASE_TRACE_SLOW_SPEED_CH15      20
#define BASE_TRACE_SLOW_SPEED_CH16      20
#define BASE_TRACE_SLOW_SPEED_CH17      20
#define BASE_TRACE_SLOW_SPEED_CH18      20
#define BASE_TRACE_SLOW_SPEED_CH19      20
#define BASE_TRACE_SLOW_SPEED_CH20      20
#define BASE_TRACE_SLOW_SPEED_CH21      20
#define BASE_TRACE_SLOW_SPEED_CH22      20
#define BASE_TRACE_SLOW_SPEED_CH23      20

#define FILTER_IIR_GAIN_CH00            0
#define FILTER_IIR_GAIN_CH01            0
#define FILTER_IIR_GAIN_CH02            0
#define FILTER_IIR_GAIN_CH03            0
#define FILTER_IIR_GAIN_CH04            0
#define FILTER_IIR_GAIN_CH05            0
#define FILTER_IIR_GAIN_CH06            0
#define FILTER_IIR_GAIN_CH07            0
#define FILTER_IIR_GAIN_CH08            0
#define FILTER_IIR_GAIN_CH09            0
#define FILTER_IIR_GAIN_CH10            0
#define FILTER_IIR_GAIN_CH11            0
#define FILTER_IIR_GAIN_CH12            0
#define FILTER_IIR_GAIN_CH13            0
#define FILTER_IIR_GAIN_CH14            0
#define FILTER_IIR_GAIN_CH15            0
#define FILTER_IIR_GAIN_CH16            0
#define FILTER_IIR_GAIN_CH17            0
#define FILTER_IIR_GAIN_CH18            0
#define FILTER_IIR_GAIN_CH19            0
#define FILTER_IIR_GAIN_CH20            0
#define FILTER_IIR_GAIN_CH21            0
#define FILTER_IIR_GAIN_CH22            0
#define FILTER_IIR_GAIN_CH23            0

#define DETECT_DEBOUNCE_CNT_CH00        1
#define DETECT_DEBOUNCE_CNT_CH01        1
#define DETECT_DEBOUNCE_CNT_CH02        1
#define DETECT_DEBOUNCE_CNT_CH03        1
#define DETECT_DEBOUNCE_CNT_CH04        1
#define DETECT_DEBOUNCE_CNT_CH05        1
#define DETECT_DEBOUNCE_CNT_CH06        1
#define DETECT_DEBOUNCE_CNT_CH07        1
#define DETECT_DEBOUNCE_CNT_CH08        1
#define DETECT_DEBOUNCE_CNT_CH09        1
#define DETECT_DEBOUNCE_CNT_CH10        1
#define DETECT_DEBOUNCE_CNT_CH11        1
#define DETECT_DEBOUNCE_CNT_CH12        1
#define DETECT_DEBOUNCE_CNT_CH13        1
#define DETECT_DEBOUNCE_CNT_CH14        1
#define DETECT_DEBOUNCE_CNT_CH15        1
#define DETECT_DEBOUNCE_CNT_CH16        1
#define DETECT_DEBOUNCE_CNT_CH17        1
#define DETECT_DEBOUNCE_CNT_CH18        1
#define DETECT_DEBOUNCE_CNT_CH19        1
#define DETECT_DEBOUNCE_CNT_CH20        1
#define DETECT_DEBOUNCE_CNT_CH21        1
#define DETECT_DEBOUNCE_CNT_CH22        1
#define DETECT_DEBOUNCE_CNT_CH23        1

#define RELEASE_DEBOUNCE_CNT_CH00       1
#define RELEASE_DEBOUNCE_CNT_CH01       1
#define RELEASE_DEBOUNCE_CNT_CH02       1
#define RELEASE_DEBOUNCE_CNT_CH03       1
#define RELEASE_DEBOUNCE_CNT_CH04       1
#define RELEASE_DEBOUNCE_CNT_CH05       1
#define RELEASE_DEBOUNCE_CNT_CH06       1
#define RELEASE_DEBOUNCE_CNT_CH07       1
#define RELEASE_DEBOUNCE_CNT_CH08       1
#define RELEASE_DEBOUNCE_CNT_CH09       1
#define RELEASE_DEBOUNCE_CNT_CH10       1
#define RELEASE_DEBOUNCE_CNT_CH11       1
#define RELEASE_DEBOUNCE_CNT_CH12       1
#define RELEASE_DEBOUNCE_CNT_CH13       1
#define RELEASE_DEBOUNCE_CNT_CH14       1
#define RELEASE_DEBOUNCE_CNT_CH15       1
#define RELEASE_DEBOUNCE_CNT_CH16       1
#define RELEASE_DEBOUNCE_CNT_CH17       1
#define RELEASE_DEBOUNCE_CNT_CH18       1
#define RELEASE_DEBOUNCE_CNT_CH19       1
#define RELEASE_DEBOUNCE_CNT_CH20       1
#define RELEASE_DEBOUNCE_CNT_CH21       1
#define RELEASE_DEBOUNCE_CNT_CH22       1
#define RELEASE_DEBOUNCE_CNT_CH23       1

#define REF_GAIN_CH00   100     
#define REF_GAIN_CH01   100  
#define REF_GAIN_CH02   100 
#define REF_GAIN_CH03   100
#define REF_GAIN_CH04   100
#define REF_GAIN_CH05   100
#define REF_GAIN_CH06   100
#define REF_GAIN_CH07   100
#define REF_GAIN_CH08   100
#define REF_GAIN_CH09   100
#define REF_GAIN_CH10   100
#define REF_GAIN_CH11   100
#define REF_GAIN_CH12   100
#define REF_GAIN_CH13   100
#define REF_GAIN_CH14   100
#define REF_GAIN_CH15   100
#define REF_GAIN_CH16   100
#define REF_GAIN_CH17   100
#define REF_GAIN_CH18   100
#define REF_GAIN_CH19   100
#define REF_GAIN_CH20   100
#define REF_GAIN_CH21   100
#define REF_GAIN_CH22   100
#define REF_GAIN_CH23   100

#define REF_DIRECTION_CH00   0     // 0: Follow, 1: Reverse
#define REF_DIRECTION_CH01   0     
#define REF_DIRECTION_CH02   0     
#define REF_DIRECTION_CH03   0     
#define REF_DIRECTION_CH04   0     
#define REF_DIRECTION_CH05   0     
#define REF_DIRECTION_CH06   0     
#define REF_DIRECTION_CH07   0     
#define REF_DIRECTION_CH08   0     
#define REF_DIRECTION_CH09   0     
#define REF_DIRECTION_CH10   0     
#define REF_DIRECTION_CH11   0     
#define REF_DIRECTION_CH12   0     
#define REF_DIRECTION_CH13   0     
#define REF_DIRECTION_CH14   0     
#define REF_DIRECTION_CH15   0     
#define REF_DIRECTION_CH16   0     
#define REF_DIRECTION_CH17   0     
#define REF_DIRECTION_CH18   0     
#define REF_DIRECTION_CH19   0     
#define REF_DIRECTION_CH20   0     
#define REF_DIRECTION_CH21   0     
#define REF_DIRECTION_CH22   0     
#define REF_DIRECTION_CH23   0     

/******************************************************************************************************/

uint32_t TS_COM_CFG[TOUCH_COM_CFG_MAX] = {
    ACT_KEY_BIT_VAL,              
    TOUCH_CLK_VAL,
    TOUCH_CLK_OFFSET_VAL,
    TOUCH_MODE_VAL,
    TOUCH_PORT_SEL_VAL,
    TOUCH_VHS_VAL,
    TOUCH_COMP_REFV_VAL,
    TIMER_STARTUP_VAL,
    TIMER_BASE_SAMPLE_VAL,
    TIMER_BASE_REVERSE_SAMPLE_VAL,
    BASE_RELEASE_HOLD_CNT_VAL,    
    MESH_SHIELD_EN,
    CH_SHIELD_EN,
    CH_SHIELD_BIT_VAL,
    REF_CH_EN,    
    REF_CH_BIT_VAL,
    REF_CH_SUM_CNT_VAL,    
    REF_CH_LPF_C_VAL,
    REF_CH_LPF_R_VAL,
};


uint32_t TS_CH_CFG[24][TOUCH_CH_CFG_MAX] = {
{TOUCH_SUM_CNT_CH00, TOUCH_LPF_C_CH00, TOUCH_LPF_R_CH00, THD_DETECT_CH00, THD_RELEASE_RATE_CH00, THD_REVERSE_RATE_CH00, BASE_TRACE_SPEED_CHECK_RATE_CH00, BASE_TRACE_FAST_SPEED_CH00, BASE_TRACE_SLOW_SPEED_CH00, FILTER_IIR_GAIN_CH00, DETECT_DEBOUNCE_CNT_CH00, RELEASE_DEBOUNCE_CNT_CH00, REF_GAIN_CH00, REF_DIRECTION_CH00},
{TOUCH_SUM_CNT_CH01, TOUCH_LPF_C_CH01, TOUCH_LPF_R_CH01, THD_DETECT_CH01, THD_RELEASE_RATE_CH01, THD_REVERSE_RATE_CH01, BASE_TRACE_SPEED_CHECK_RATE_CH01, BASE_TRACE_FAST_SPEED_CH01, BASE_TRACE_SLOW_SPEED_CH01, FILTER_IIR_GAIN_CH01, DETECT_DEBOUNCE_CNT_CH01, RELEASE_DEBOUNCE_CNT_CH01, REF_GAIN_CH01, REF_DIRECTION_CH01},
{TOUCH_SUM_CNT_CH02, TOUCH_LPF_C_CH02, TOUCH_LPF_R_CH02, THD_DETECT_CH02, THD_RELEASE_RATE_CH02, THD_REVERSE_RATE_CH02, BASE_TRACE_SPEED_CHECK_RATE_CH02, BASE_TRACE_FAST_SPEED_CH02, BASE_TRACE_SLOW_SPEED_CH02, FILTER_IIR_GAIN_CH02, DETECT_DEBOUNCE_CNT_CH02, RELEASE_DEBOUNCE_CNT_CH02, REF_GAIN_CH02, REF_DIRECTION_CH02},
{TOUCH_SUM_CNT_CH03, TOUCH_LPF_C_CH03, TOUCH_LPF_R_CH03, THD_DETECT_CH03, THD_RELEASE_RATE_CH03, THD_REVERSE_RATE_CH03, BASE_TRACE_SPEED_CHECK_RATE_CH03, BASE_TRACE_FAST_SPEED_CH03, BASE_TRACE_SLOW_SPEED_CH03, FILTER_IIR_GAIN_CH03, DETECT_DEBOUNCE_CNT_CH03, RELEASE_DEBOUNCE_CNT_CH03, REF_GAIN_CH03, REF_DIRECTION_CH03},
{TOUCH_SUM_CNT_CH04, TOUCH_LPF_C_CH04, TOUCH_LPF_R_CH04, THD_DETECT_CH04, THD_RELEASE_RATE_CH04, THD_REVERSE_RATE_CH04, BASE_TRACE_SPEED_CHECK_RATE_CH04, BASE_TRACE_FAST_SPEED_CH04, BASE_TRACE_SLOW_SPEED_CH04, FILTER_IIR_GAIN_CH04, DETECT_DEBOUNCE_CNT_CH04, RELEASE_DEBOUNCE_CNT_CH04, REF_GAIN_CH04, REF_DIRECTION_CH04},
{TOUCH_SUM_CNT_CH05, TOUCH_LPF_C_CH05, TOUCH_LPF_R_CH05, THD_DETECT_CH05, THD_RELEASE_RATE_CH05, THD_REVERSE_RATE_CH05, BASE_TRACE_SPEED_CHECK_RATE_CH05, BASE_TRACE_FAST_SPEED_CH05, BASE_TRACE_SLOW_SPEED_CH05, FILTER_IIR_GAIN_CH05, DETECT_DEBOUNCE_CNT_CH05, RELEASE_DEBOUNCE_CNT_CH05, REF_GAIN_CH05, REF_DIRECTION_CH05},
{TOUCH_SUM_CNT_CH06, TOUCH_LPF_C_CH06, TOUCH_LPF_R_CH06, THD_DETECT_CH06, THD_RELEASE_RATE_CH06, THD_REVERSE_RATE_CH06, BASE_TRACE_SPEED_CHECK_RATE_CH06, BASE_TRACE_FAST_SPEED_CH06, BASE_TRACE_SLOW_SPEED_CH06, FILTER_IIR_GAIN_CH06, DETECT_DEBOUNCE_CNT_CH06, RELEASE_DEBOUNCE_CNT_CH06, REF_GAIN_CH06, REF_DIRECTION_CH06},
{TOUCH_SUM_CNT_CH07, TOUCH_LPF_C_CH07, TOUCH_LPF_R_CH07, THD_DETECT_CH07, THD_RELEASE_RATE_CH07, THD_REVERSE_RATE_CH07, BASE_TRACE_SPEED_CHECK_RATE_CH07, BASE_TRACE_FAST_SPEED_CH07, BASE_TRACE_SLOW_SPEED_CH07, FILTER_IIR_GAIN_CH07, DETECT_DEBOUNCE_CNT_CH07, RELEASE_DEBOUNCE_CNT_CH07, REF_GAIN_CH07, REF_DIRECTION_CH07},
{TOUCH_SUM_CNT_CH08, TOUCH_LPF_C_CH08, TOUCH_LPF_R_CH08, THD_DETECT_CH08, THD_RELEASE_RATE_CH08, THD_REVERSE_RATE_CH08, BASE_TRACE_SPEED_CHECK_RATE_CH08, BASE_TRACE_FAST_SPEED_CH08, BASE_TRACE_SLOW_SPEED_CH08, FILTER_IIR_GAIN_CH08, DETECT_DEBOUNCE_CNT_CH08, RELEASE_DEBOUNCE_CNT_CH08, REF_GAIN_CH08, REF_DIRECTION_CH08},
{TOUCH_SUM_CNT_CH09, TOUCH_LPF_C_CH09, TOUCH_LPF_R_CH09, THD_DETECT_CH09, THD_RELEASE_RATE_CH09, THD_REVERSE_RATE_CH09, BASE_TRACE_SPEED_CHECK_RATE_CH09, BASE_TRACE_FAST_SPEED_CH09, BASE_TRACE_SLOW_SPEED_CH09, FILTER_IIR_GAIN_CH09, DETECT_DEBOUNCE_CNT_CH09, RELEASE_DEBOUNCE_CNT_CH09, REF_GAIN_CH09, REF_DIRECTION_CH09},
{TOUCH_SUM_CNT_CH10, TOUCH_LPF_C_CH10, TOUCH_LPF_R_CH10, THD_DETECT_CH10, THD_RELEASE_RATE_CH10, THD_REVERSE_RATE_CH10, BASE_TRACE_SPEED_CHECK_RATE_CH10, BASE_TRACE_FAST_SPEED_CH10, BASE_TRACE_SLOW_SPEED_CH10, FILTER_IIR_GAIN_CH10, DETECT_DEBOUNCE_CNT_CH10, RELEASE_DEBOUNCE_CNT_CH10, REF_GAIN_CH10, REF_DIRECTION_CH10},
{TOUCH_SUM_CNT_CH11, TOUCH_LPF_C_CH11, TOUCH_LPF_R_CH11, THD_DETECT_CH11, THD_RELEASE_RATE_CH11, THD_REVERSE_RATE_CH11, BASE_TRACE_SPEED_CHECK_RATE_CH11, BASE_TRACE_FAST_SPEED_CH11, BASE_TRACE_SLOW_SPEED_CH11, FILTER_IIR_GAIN_CH11, DETECT_DEBOUNCE_CNT_CH11, RELEASE_DEBOUNCE_CNT_CH11, REF_GAIN_CH11, REF_DIRECTION_CH11},
{TOUCH_SUM_CNT_CH12, TOUCH_LPF_C_CH12, TOUCH_LPF_R_CH12, THD_DETECT_CH12, THD_RELEASE_RATE_CH12, THD_REVERSE_RATE_CH12, BASE_TRACE_SPEED_CHECK_RATE_CH12, BASE_TRACE_FAST_SPEED_CH12, BASE_TRACE_SLOW_SPEED_CH12, FILTER_IIR_GAIN_CH12, DETECT_DEBOUNCE_CNT_CH12, RELEASE_DEBOUNCE_CNT_CH12, REF_GAIN_CH12, REF_DIRECTION_CH12},
{TOUCH_SUM_CNT_CH13, TOUCH_LPF_C_CH13, TOUCH_LPF_R_CH13, THD_DETECT_CH13, THD_RELEASE_RATE_CH13, THD_REVERSE_RATE_CH13, BASE_TRACE_SPEED_CHECK_RATE_CH13, BASE_TRACE_FAST_SPEED_CH13, BASE_TRACE_SLOW_SPEED_CH13, FILTER_IIR_GAIN_CH13, DETECT_DEBOUNCE_CNT_CH13, RELEASE_DEBOUNCE_CNT_CH13, REF_GAIN_CH13, REF_DIRECTION_CH13},
{TOUCH_SUM_CNT_CH14, TOUCH_LPF_C_CH14, TOUCH_LPF_R_CH14, THD_DETECT_CH14, THD_RELEASE_RATE_CH14, THD_REVERSE_RATE_CH14, BASE_TRACE_SPEED_CHECK_RATE_CH14, BASE_TRACE_FAST_SPEED_CH14, BASE_TRACE_SLOW_SPEED_CH14, FILTER_IIR_GAIN_CH14, DETECT_DEBOUNCE_CNT_CH14, RELEASE_DEBOUNCE_CNT_CH14, REF_GAIN_CH14, REF_DIRECTION_CH14},
{TOUCH_SUM_CNT_CH15, TOUCH_LPF_C_CH15, TOUCH_LPF_R_CH15, THD_DETECT_CH15, THD_RELEASE_RATE_CH15, THD_REVERSE_RATE_CH15, BASE_TRACE_SPEED_CHECK_RATE_CH15, BASE_TRACE_FAST_SPEED_CH15, BASE_TRACE_SLOW_SPEED_CH15, FILTER_IIR_GAIN_CH15, DETECT_DEBOUNCE_CNT_CH15, RELEASE_DEBOUNCE_CNT_CH15, REF_GAIN_CH15, REF_DIRECTION_CH15},
{TOUCH_SUM_CNT_CH16, TOUCH_LPF_C_CH16, TOUCH_LPF_R_CH16, THD_DETECT_CH16, THD_RELEASE_RATE_CH16, THD_REVERSE_RATE_CH16, BASE_TRACE_SPEED_CHECK_RATE_CH16, BASE_TRACE_FAST_SPEED_CH16, BASE_TRACE_SLOW_SPEED_CH16, FILTER_IIR_GAIN_CH16, DETECT_DEBOUNCE_CNT_CH16, RELEASE_DEBOUNCE_CNT_CH16, REF_GAIN_CH16, REF_DIRECTION_CH16},
{TOUCH_SUM_CNT_CH17, TOUCH_LPF_C_CH17, TOUCH_LPF_R_CH17, THD_DETECT_CH17, THD_RELEASE_RATE_CH17, THD_REVERSE_RATE_CH17, BASE_TRACE_SPEED_CHECK_RATE_CH17, BASE_TRACE_FAST_SPEED_CH17, BASE_TRACE_SLOW_SPEED_CH17, FILTER_IIR_GAIN_CH17, DETECT_DEBOUNCE_CNT_CH17, RELEASE_DEBOUNCE_CNT_CH17, REF_GAIN_CH17, REF_DIRECTION_CH17},
{TOUCH_SUM_CNT_CH18, TOUCH_LPF_C_CH18, TOUCH_LPF_R_CH18, THD_DETECT_CH18, THD_RELEASE_RATE_CH18, THD_REVERSE_RATE_CH18, BASE_TRACE_SPEED_CHECK_RATE_CH18, BASE_TRACE_FAST_SPEED_CH18, BASE_TRACE_SLOW_SPEED_CH18, FILTER_IIR_GAIN_CH18, DETECT_DEBOUNCE_CNT_CH18, RELEASE_DEBOUNCE_CNT_CH18, REF_GAIN_CH18, REF_DIRECTION_CH18},
{TOUCH_SUM_CNT_CH19, TOUCH_LPF_C_CH19, TOUCH_LPF_R_CH19, THD_DETECT_CH19, THD_RELEASE_RATE_CH19, THD_REVERSE_RATE_CH19, BASE_TRACE_SPEED_CHECK_RATE_CH19, BASE_TRACE_FAST_SPEED_CH19, BASE_TRACE_SLOW_SPEED_CH19, FILTER_IIR_GAIN_CH19, DETECT_DEBOUNCE_CNT_CH19, RELEASE_DEBOUNCE_CNT_CH19, REF_GAIN_CH19, REF_DIRECTION_CH19},
{TOUCH_SUM_CNT_CH20, TOUCH_LPF_C_CH20, TOUCH_LPF_R_CH20, THD_DETECT_CH20, THD_RELEASE_RATE_CH20, THD_REVERSE_RATE_CH20, BASE_TRACE_SPEED_CHECK_RATE_CH20, BASE_TRACE_FAST_SPEED_CH20, BASE_TRACE_SLOW_SPEED_CH20, FILTER_IIR_GAIN_CH20, DETECT_DEBOUNCE_CNT_CH20, RELEASE_DEBOUNCE_CNT_CH20, REF_GAIN_CH20, REF_DIRECTION_CH20},
{TOUCH_SUM_CNT_CH21, TOUCH_LPF_C_CH21, TOUCH_LPF_R_CH21, THD_DETECT_CH21, THD_RELEASE_RATE_CH21, THD_REVERSE_RATE_CH21, BASE_TRACE_SPEED_CHECK_RATE_CH21, BASE_TRACE_FAST_SPEED_CH21, BASE_TRACE_SLOW_SPEED_CH21, FILTER_IIR_GAIN_CH21, DETECT_DEBOUNCE_CNT_CH21, RELEASE_DEBOUNCE_CNT_CH21, REF_GAIN_CH21, REF_DIRECTION_CH21},
{TOUCH_SUM_CNT_CH22, TOUCH_LPF_C_CH22, TOUCH_LPF_R_CH22, THD_DETECT_CH22, THD_RELEASE_RATE_CH22, THD_REVERSE_RATE_CH22, BASE_TRACE_SPEED_CHECK_RATE_CH22, BASE_TRACE_FAST_SPEED_CH22, BASE_TRACE_SLOW_SPEED_CH22, FILTER_IIR_GAIN_CH22, DETECT_DEBOUNCE_CNT_CH22, RELEASE_DEBOUNCE_CNT_CH22, REF_GAIN_CH22, REF_DIRECTION_CH22},
{TOUCH_SUM_CNT_CH23, TOUCH_LPF_C_CH23, TOUCH_LPF_R_CH23, THD_DETECT_CH23, THD_RELEASE_RATE_CH23, THD_REVERSE_RATE_CH23, BASE_TRACE_SPEED_CHECK_RATE_CH23, BASE_TRACE_FAST_SPEED_CH23, BASE_TRACE_SLOW_SPEED_CH23, FILTER_IIR_GAIN_CH23, DETECT_DEBOUNCE_CNT_CH23, RELEASE_DEBOUNCE_CNT_CH23, REF_GAIN_CH23, REF_DIRECTION_CH23},
};


#endif  /* _TOUCH_CONFIG_H_ */


