; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --debug -c -S --gnu -o.\objects\touch.s --depend=.\objects\touch.d --cpu=Cortex-M0+ --apcs=interwork -O0 --diag_suppress=9931 -I..\..\..\..\..\core\device\a31t21x\include -I..\..\..\..\..\driver\a31t21x\include -I..\..\code_app\library\header -I..\..\common -I..\..\..\..\..\core\cmsis\include -I..\..\code_app -D__UVISION_VERSION=526 -DARMCM0P --omf_browse=.\objects\touch.crf ..\..\code_lib\touch.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

__NVIC_DisableIRQ PROC
        CMP      r0,#0
        BLT      |L0.48|
        LSLS     r2,r0,#27
        LSRS     r2,r2,#27
        MOVS     r1,#1
        LSLS     r1,r1,r2
        LDR      r2,|L0.1008|
        STR      r1,[r2,#0]
        NOP      
        NOP      
        NOP      
        DSB      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        ISB      
        NOP      
        NOP      
        NOP      
|L0.48|
        BX       lr
        ENDP

TOUCH_IRQHandler PROC
        PUSH     {r4,lr}
        LDR      r0,|L0.1012|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#24
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.128|
        LDR      r0,|L0.1016|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#8
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L0.128|
        LDR      r0,|L0.1020|
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#6
        BICS     r0,r0,r1
        ADDS     r0,r0,#2
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
        MOVS     r0,#0x1d
        BL       __NVIC_DisableIRQ
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#0x40]
        MOVS     r1,#1
        LSLS     r1,r1,#24
        BICS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0x40]
        LDR      r0,|L0.1016|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#9
        BICS     r0,r0,r1
        LDR      r1,|L0.1016|
        STR      r0,[r1,#0x20]
|L0.126|
        POP      {r4,pc}
|L0.128|
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        LDRB     r0,[r0,#0x10]  ; ts
        CMP      r0,#1
        BNE      |L0.192|
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r0,[r0,#0x68]  ; ts
        LDRB     r4,[r0,#0]
        LSLS     r0,r4,#3
        LDR      r1,|L0.1024|
        ADDS     r0,r0,r1
        LDR      r0,[r0,#0]
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0xc0
        LDR      r1,[r1,#0x20]  ; ts
        STR      r0,[r1,#0]
        LSLS     r0,r4,#1
        ADDS     r0,r0,#1
        LSLS     r0,r0,#2
        LDR      r1,|L0.1024|
        ADDS     r0,r0,r1
        LDR      r0,[r0,#0]
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0xc0
        LDR      r1,[r1,#0x20]  ; ts
        STR      r0,[r1,#4]
        MOVS     r1,#2
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        STRB     r1,[r0,#0x10]
        B        |L0.254|
|L0.192|
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r1,[r0,#0x4c]  ; ts
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0]  ; ts
        LDRB     r4,[r1,r0]
        LSLS     r0,r4,#3
        LDR      r1,|L0.1024|
        ADDS     r0,r0,r1
        LDR      r1,[r0,#0]
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r2,[r0,#0x1c]  ; ts
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0]  ; ts
        LSLS     r0,r0,#3
        STR      r1,[r2,r0]
        LSLS     r0,r4,#1
        ADDS     r0,r0,#1
        LSLS     r0,r0,#2
        LDR      r1,|L0.1024|
        ADDS     r0,r0,r1
        LDR      r1,[r0,#0]
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r2,[r0,#0x1c]  ; ts
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0]  ; ts
        LSLS     r0,r0,#3
        ADDS     r0,r2,r0
        STR      r1,[r0,#4]
|L0.254|
        MOVS     r0,#0
        LDR      r1,|L0.1016|
        STR      r0,[r1,#0x20]
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        LDRB     r0,[r0,#0]  ; ts
        ADDS     r0,r0,#1
        UXTB     r1,r0
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        STRB     r1,[r0,#0]
        LDRB     r0,[r0,#0x10]  ; ts
        CMP      r0,#2
        BNE      |L0.314|
        LDR      r0,|L0.1020|
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#6
        BICS     r0,r0,r1
        ADDS     r0,r0,#4
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
        MOVS     r1,#0
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        STRB     r1,[r0,#0]
        STRB     r1,[r0,#0x10]
        MOVS     r0,#0x1d
        BL       __NVIC_DisableIRQ
        B        |L0.462|
|L0.314|
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        LDRB     r1,[r0,#0]  ; ts
        LDRB     r0,[r0,#1]  ; ts
        CMP      r1,r0
        BNE      |L0.418|
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r0,[r0,#0x6c]  ; ts
        CMP      r0,#0
        BNE      |L0.368|
        LDR      r0,|L0.1020|
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#6
        BICS     r0,r0,r1
        ADDS     r0,r0,#4
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
        MOVS     r1,#0
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        STRB     r1,[r0,#0]
        STRB     r1,[r0,#0x10]
        MOVS     r0,#0x1d
        BL       __NVIC_DisableIRQ
        B        |L0.462|
|L0.368|
        MOVS     r1,#0
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0xc]
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r0,[r0,#0x68]  ; ts
        LDRB     r4,[r0,#0]
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#0xc]
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ORRS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0xc]
        MOVS     r0,#0x11
        LDR      r1,|L0.1016|
        STR      r0,[r1,#0x20]
        MOVS     r1,#1
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0x60
        STRB     r1,[r0,#0x10]
        B        |L0.462|
|L0.418|
        MOVS     r1,#0
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0xc]
        LDR      r0,|L0.1020|
        SUBS     r0,r0,#0xc0
        LDR      r1,[r0,#0x4c]  ; ts
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0]  ; ts
        LDRB     r4,[r1,r0]
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#0xc]
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ORRS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0xc]
        MOVS     r0,#0x11
        LDR      r1,|L0.1016|
        STR      r0,[r1,#0x20]
|L0.462|
        NOP      
        B        |L0.126|
        ENDP

Touch_Set_Mode PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x60
        STRB     r0,[r1,#0x11]
        BX       lr
        ENDP

Touch_Set_Shield PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        LDR      r0,|L0.1020|
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
        MOV      r0,r1
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#0x20
        BICS     r0,r0,r1
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
        CMP      r4,#1
        BEQ      |L0.512|
        CMP      r5,#1
        BNE      |L0.640|
|L0.512|
        CMP      r4,#1
        BNE      |L0.544|
        LDR      r0,|L0.1020|
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#0x20
        BICS     r0,r0,r1
        ADDS     r0,r0,#0x20
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
        MOV      r0,r1
        SUBS     r0,r0,#0xc0
        LDR      r1,[r0,#0x54]  ; ts
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0x40]
        B        |L0.552|
|L0.544|
        MOVS     r1,#0
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0x40]
|L0.552|
        CMP      r5,#1
        BNE      |L0.620|
        MOVS     r2,#5
        MOVS     r1,#1
        MOVS     r0,#4
        BL       HAL_GPIO_SetFunction
        MOVS     r2,#2
        MOVS     r1,#1
        MOVS     r0,#4
        BL       HAL_GPIO_SetMode
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#0x40]
        LSLS     r1,r5,#23
        BICS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0x40]
        MOV      r0,r1
        LDR      r0,[r0,#0x40]
        LSLS     r1,r1,#26
        ORRS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0x40]
        LDR      r0,|L0.1020|
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        ADDS     r0,r0,#0x10
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#0x18]
|L0.620|
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#0x40]
        MOVS     r1,#1
        LSLS     r1,r1,#24
        ORRS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0x40]
        B        |L0.658|
|L0.640|
        LDR      r0,|L0.1016|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#0x40]
        MOVS     r1,#1
        LSLS     r1,r1,#24
        BICS     r0,r0,r1
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#0x40]
|L0.658|
        POP      {r4-r6,pc}
        ENDP

Touch_Set_Sum_Count PROC
        LDR      r1,|L0.1016|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#8]
        BX       lr
        ENDP

Touch_Set_Common_THD PROC
        MOV      r1,r0
        MOVS     r0,#0
        B        |L0.688|
|L0.674|
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0xc0
        LDR      r2,[r2,#8]  ; ts
        LSLS     r3,r0,#2
        STR      r1,[r2,r3]
        ADDS     r2,r0,#1
        UXTB     r0,r2
|L0.688|
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x60
        LDRB     r2,[r2,#1]  ; ts
        CMP      r2,r0
        BGT      |L0.674|
        BX       lr
        ENDP

Touch_Set_CH_THD PROC
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0xc0
        LDR      r2,[r2,#8]  ; ts
        LSLS     r3,r0,#2
        STR      r1,[r2,r3]
        BX       lr
        ENDP

Touch_Set_Common_POS_noise_THD PROC
        MOV      r1,r0
        LDR      r2,|L0.1028|
        CMP      r1,r2
        BLS      |L0.722|
        MOV      r1,r2
|L0.722|
        MOVS     r0,#0
        B        |L0.740|
|L0.726|
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x40
        LDR      r2,[r2,#0x48]  ; ts
        LSLS     r3,r0,#2
        STR      r1,[r2,r3]
        ADDS     r2,r0,#1
        UXTB     r0,r2
|L0.740|
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x60
        LDRB     r2,[r2,#1]  ; ts
        CMP      r2,r0
        BGT      |L0.726|
        BX       lr
        ENDP

Touch_Set_CH_POS_noise_THD PROC
        LDR      r2,|L0.1028|
        CMP      r1,r2
        BLS      |L0.760|
        MOV      r1,r2
|L0.760|
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x40
        LDR      r2,[r2,#0x48]  ; ts
        LSLS     r3,r0,#2
        STR      r1,[r2,r3]
        BX       lr
        ENDP

Touch_Set_Group_CH PROC
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x40
        LDR      r2,[r2,#0x4c]  ; ts
        STRB     r1,[r2,r0]
        BX       lr
        ENDP

Touch_Set_NoiseTHD_Rate PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r0,[r1,#4]
        BX       lr
        ENDP

Touch_Set_BaseHold_Rate PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r0,[r1,#5]
        BX       lr
        ENDP

Touch_Set_Base_Tracking PROC
        LDR      r3,|L0.1020|
        SUBS     r3,r3,#0x40
        STRB     r0,[r3,#0x11]
        STRB     r1,[r3,#0x12]
        STR      r2,[r3,#0x14]  ; ts
        BX       lr
        ENDP

Touch_Set_Hold_Key_Release_Time PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x40
        STR      r0,[r1,#0x38]  ; ts
        BX       lr
        ENDP

Touch_Set_Single_Key_Press_limit PROC
        CMP      r0,#2
        BGE      |L0.824|
        MOVS     r0,#2
|L0.824|
        LDR      r1,|L0.1020|
        STRB     r0,[r1,#4]
        BX       lr
        ENDP

Touch_Set_Release_Rate PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x60
        STRB     r0,[r1,#0x1d]
        BX       lr
        ENDP

Touch_Set_Reverse_Rate PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x60
        STRB     r0,[r1,#0x1c]
        BX       lr
        ENDP

Touch_Set_Reverse_Time PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0xc0
        STR      r0,[r1,#0x78]  ; ts
        BX       lr
        ENDP

Touch_Set_Debounce PROC
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x60
        STRB     r0,[r2,#0x13]
        STRB     r1,[r2,#0x14]
        BX       lr
        ENDP

Touch_Set_IIR PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x60
        STRB     r0,[r1,#0x15]
        BX       lr
        ENDP

Touch_Set_Init_Delay PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x40
        STR      r0,[r1,#0]  ; ts
        BX       lr
        ENDP

Touch_Set_Inact_Port PROC
        CMP      r0,#3
        BGE      |L0.892|
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r0,[r1,#6]
        B        |L0.900|
|L0.892|
        MOVS     r2,#1
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r2,[r1,#6]
|L0.900|
        BX       lr
        ENDP

Touch_Set_Frequency PROC
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r0,[r1,#7]
        BX       lr
        ENDP

Touch_Set_Comp_RefV PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOVS     r1,#5
        MOV      r0,r4
        BL       __aeabi_uidivmod
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x40
        STR      r0,[r1,#0x28]  ; ts
        POP      {r4,pc}
        ENDP

Touch_Set_VHS PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOVS     r1,#5
        MOV      r0,r4
        BL       __aeabi_uidivmod
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x40
        STR      r0,[r1,#0x2c]  ; ts
        POP      {r4,pc}
        ENDP

Touch_Set_Freq_Shift PROC
        CMP      r0,#0
        BLE      |L0.962|
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r0,[r1,#0x10]
        B        |L0.972|
|L0.962|
        LSLS     r2,r0,#26
        LSRS     r2,r2,#26
        LDR      r1,|L0.1020|
        SUBS     r1,r1,#0x20
        STRB     r2,[r1,#0x10]
|L0.972|
        BX       lr
        ENDP

Touch_Set_Common_Serial_Register PROC
        MOV      r1,r0
        MOVS     r0,#0
        B        |L0.994|
|L0.980|
        MOVS     r2,#0x70
        ORRS     r2,r2,r1
        LDR      r3,|L0.1020|
        SUBS     r3,r3,#0xc0
        LDR      r3,[r3,#0x50]  ; ts
        STRB     r2,[r3,r0]
        ADDS     r0,r0,#1
|L0.994|
        LDR      r2,|L0.1020|
        SUBS     r2,r2,#0x60
        LDRB     r2,[r2,#1]  ; ts
        CMP      r2,r0
        BHI      |L0.980|
        BX       lr
        DCW      0x0000
|L0.1008|
        DCD      0xe000e180
|L0.1012|
        DCD      t_sysbit
|L0.1016|
        DCD      0x40003700
|L0.1020|
        DCD      ||ts||+0xc0
|L0.1024|
        DCD      0x40003600
|L0.1028|
        DCD      0x00007fff
        ENDP

Touch_Set_CH_Serial_Register PROC
        MOVS     r2,#0x70
        ORRS     r2,r2,r1
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x50]  ; ts
        STRB     r2,[r3,r0]
        BX       lr
        ENDP

Touch_Get_Key PROC
        LDR      r0,|L0.2056|
        LDR      r0,[r0,#0x58]  ; ts
        BX       lr
        ENDP

Touch_Init_Variable PROC
        MOVS     r2,#0
        LDR      r3,|L0.2056|
        STRB     r2,[r3,#0]
        MOVS     r3,#0
        LDR      r2,|L0.2056|
        ADDS     r2,r2,#0x60
        STRB     r3,[r2,#0]
        STRB     r3,[r2,#0x10]
        MOVS     r2,#0
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x24]  ; ts
        STR      r2,[r3,#0]
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x24]  ; ts
        STR      r2,[r3,#4]
        MOVS     r1,#0
        B        |L0.1102|
|L0.1084|
        MOVS     r2,#0
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x44]  ; ts
        STRB     r2,[r3,r1]
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x48]  ; ts
        STRB     r2,[r3,r1]
        ADDS     r2,r1,#1
        UXTB     r1,r2
|L0.1102|
        LDR      r2,|L0.2056|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#1]  ; ts
        CMP      r2,r1
        BGT      |L0.1084|
        LDR      r2,|L0.2056|
        ADDS     r2,r2,#0xc0
        LDRB     r2,[r2,#0x18]  ; ts
        LSRS     r2,r2,#1
        LSLS     r2,r2,#1
        LDR      r3,|L0.2056|
        ADDS     r3,r3,#0xc0
        STRB     r2,[r3,#0x18]
        MOVS     r2,#0
        SUBS     r3,r3,#0xc0
        STR      r2,[r3,#0x5c]  ; ts
        STR      r2,[r3,#0x58]  ; ts
        MOVS     r3,#0xff
        LDR      r2,|L0.2056|
        ADDS     r2,r2,#0x80
        STRB     r3,[r2,#4]
        SUBS     r2,r2,#0x80
        LDR      r2,[r2,#0x6c]  ; ts
        CMP      r2,#0
        BEQ      |L0.1188|
        MOVS     r0,#0
        B        |L0.1182|
|L0.1156|
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x6c]  ; ts
        MOVS     r3,#1
        LSLS     r3,r3,r0
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.1178|
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x68]  ; ts
        STRB     r0,[r2,#0]
        B        |L0.1186|
|L0.1178|
        ADDS     r2,r0,#1
        UXTB     r0,r2
|L0.1182|
        CMP      r0,#0x18
        BLT      |L0.1156|
|L0.1186|
        NOP      
|L0.1188|
        MOVS     r1,#0
        B        |L0.1234|
|L0.1192|
        MOVS     r0,#0
        B        |L0.1224|
|L0.1196|
        LSLS     r2,r1,#2
        LDR      r3,|L0.2060|
        LDR      r2,[r3,r2]
        MOVS     r3,#1
        LSLS     r3,r3,r0
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.1220|
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        STRB     r0,[r2,r1]
        B        |L0.1228|
|L0.1220|
        ADDS     r2,r0,#1
        UXTB     r0,r2
|L0.1224|
        CMP      r0,#0x18
        BLT      |L0.1196|
|L0.1228|
        NOP      
        ADDS     r2,r1,#1
        UXTB     r1,r2
|L0.1234|
        LDR      r2,|L0.2056|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#1]  ; ts
        CMP      r2,r1
        BGT      |L0.1192|
        BX       lr
        ENDP

Touch_Init_Register PROC
        PUSH     {r4,r5,lr}
        MOVS     r3,#0
        LDR      r4,|L0.2064|
        STR      r3,[r4,#0x20]
        MOVS     r4,#0xff
        ADDS     r4,r4,#0xa1
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r4,[r3,#4]
        LDR      r4,[r3,#4]
        LDR      r3,|L0.2056|
        ADDS     r3,r3,#0xa0
        LDRB     r3,[r3,#6]  ; ts
        ADDS     r4,r4,r3
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r4,[r3,#4]
        LDR      r3,|L0.2068|
        LDRB     r3,[r3,#0]  ; t_sysbit
        LSLS     r3,r3,#24
        LSRS     r3,r3,#31
        CMP      r3,#0
        BNE      |L0.1310|
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        LDR      r3,[r3,#4]
        MOVS     r4,#0xff
        ADDS     r4,#1
        BICS     r3,r3,r4
        LDR      r4,|L0.2064|
        ADDS     r4,r4,#0x20
        STR      r3,[r4,#4]
|L0.1310|
        LDR      r3,|L0.2056|
        ADDS     r3,r3,#0x80
        LDR      r4,[r3,#0x2c]  ; ts
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r4,[r3,#0x2c]
        MOVS     r4,#0xff
        STR      r4,[r3,#0x10]
        MOVS     r4,#0x74
        STR      r4,[r3,#0x14]
        LDR      r3,|L0.2056|
        ADDS     r3,r3,#0x80
        LDR      r4,[r3,#0x28]  ; ts
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r4,[r3,#0x30]
        MOVS     r4,#8
        STR      r4,[r3,#0x18]
        LDR      r3,|L0.2056|
        ADDS     r3,r3,#0xa0
        LDRB     r3,[r3,#7]  ; ts
        MOVS     r4,#0xff
        ADDS     r4,r4,#0x81
        ORRS     r3,r3,r4
        LDR      r4,|L0.2064|
        ADDS     r4,r4,#0x20
        STR      r3,[r4,#0x1c]
        MOVS     r4,#0x20
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r4,[r3,#0x20]
        LDR      r3,|L0.2056|
        ADDS     r3,r3,#0xa0
        LDRB     r4,[r3,#0x10]  ; ts
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r4,[r3,#0x24]
        MOVS     r4,#0
        STR      r4,[r3,#0x28]
        MOVS     r1,#0
        MOVS     r0,#0
        B        |L0.1464|
|L0.1394|
        CMP      r0,#3
        BEQ      |L0.1402|
        CMP      r0,#0x10
        BNE      |L0.1440|
|L0.1402|
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        LSLS     r4,r0,#2
        LDR      r2,[r3,r4]
        LSRS     r3,r2,#16
        MOV      r4,r1
        ADDS     r5,r1,#1
        UXTB     r1,r5
        LSLS     r5,r4,#2
        LDR      r4,|L0.2072|
        STR      r3,[r4,r5]
        UXTH     r5,r2
        MOV      r4,r1
        ADDS     r3,r1,#1
        UXTB     r1,r3
        LSLS     r4,r4,#2
        LDR      r3,|L0.2072|
        STR      r5,[r3,r4]
        B        |L0.1460|
|L0.1440|
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        LSLS     r4,r0,#2
        LDR      r5,[r3,r4]
        MOV      r4,r1
        ADDS     r3,r1,#1
        UXTB     r1,r3
        LSLS     r4,r4,#2
        LDR      r3,|L0.2072|
        STR      r5,[r3,r4]
|L0.1460|
        ADDS     r3,r0,#1
        UXTB     r0,r3
|L0.1464|
        CMP      r0,#0x11
        BLT      |L0.1394|
        POP      {r4,r5,pc}
        ENDP

Touch_Get_Single_CH PROC
        PUSH     {r4,lr}
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r1,[r2,r0]
        LDR      r2,|L0.2064|
        ADDS     r2,r2,#0x20
        LDR      r2,[r2,#0xc]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        ORRS     r2,r2,r3
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r2,[r3,#0xc]
        MOVS     r2,#0x11
        LDR      r3,|L0.2064|
        STR      r2,[r3,#0x20]
        NOP      
|L0.1504|
        LDR      r2,|L0.2064|
        LDR      r2,[r2,#0x20]
        MOVS     r3,#4
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.1504|
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r0]
        LSLS     r2,r2,#3
        LDR      r3,|L0.2076|
        ADDS     r2,r2,r3
        LDR      r2,[r2,#0]
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x1c]  ; ts
        LSLS     r4,r0,#3
        STR      r2,[r3,r4]
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r0]
        LSLS     r2,r2,#1
        ADDS     r2,r2,#1
        LSLS     r2,r2,#2
        LDR      r3,|L0.2076|
        ADDS     r2,r2,r3
        LDR      r2,[r2,#0]
        LDR      r3,|L0.2056|
        LDR      r3,[r3,#0x1c]  ; ts
        LSLS     r4,r0,#3
        ADDS     r3,r3,r4
        STR      r2,[r3,#4]
        MOVS     r2,#0
        LDR      r3,|L0.2064|
        STR      r2,[r3,#0x20]
        LDR      r2,|L0.2064|
        ADDS     r2,r2,#0x20
        LDR      r2,[r2,#0xc]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        BICS     r2,r2,r3
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r2,[r3,#0xc]
        POP      {r4,pc}
        ENDP

Touch_Start_Touch PROC
        PUSH     {r4,lr}
        LDR      r1,|L0.2056|
        LDR      r1,[r1,#0x4c]  ; ts
        LDRB     r2,[r1,r0]
        MOVS     r3,#0
        LDR      r1,|L0.2064|
        ADDS     r1,r1,#0x20
        STR      r3,[r1,#0xc]
        LDR      r1,[r1,#0xc]
        MOVS     r3,#1
        LSLS     r3,r3,r2
        ORRS     r1,r1,r3
        LDR      r3,|L0.2064|
        ADDS     r3,r3,#0x20
        STR      r1,[r3,#0xc]
        LDR      r1,|L0.2056|
        ADDS     r1,r1,#0xd8
        LDRB     r1,[r1,#1]
        LSRS     r1,r1,#7
        CMP      r1,#0
        BEQ      |L0.1646|
        LDR      r1,|L0.2056|
        LDR      r1,[r1,#0x50]  ; ts
        LDRB     r3,[r1,r0]
        LDR      r1,|L0.2064|
        ADDS     r1,r1,#0x20
        STR      r3,[r1,#0x14]
|L0.1646|
        LDR      r1,|L0.2068|
        LDR      r1,[r1,#0]  ; t_sysbit
        MOVS     r3,#8
        BICS     r1,r1,r3
        LDR      r3,|L0.2068|
        STR      r1,[r3,#0]  ; t_sysbit
        MOVS     r1,#0x1d
        CMP      r1,#0
        BLT      |L0.1676|
        LSLS     r4,r1,#27
        LSRS     r4,r4,#27
        MOVS     r3,#1
        LSLS     r3,r3,r4
        LDR      r4,|L0.2080|
        STR      r3,[r4,#0]
|L0.1676|
        NOP      
        MOVS     r1,#0x1d
        CMP      r1,#0
        BLT      |L0.1704|
        NOP      
        NOP      
        LSLS     r4,r1,#27
        LSRS     r4,r4,#27
        MOVS     r3,#1
        LSLS     r3,r3,r4
        LDR      r4,|L0.2084|
        STR      r3,[r4,#0]
        NOP      
        NOP      
|L0.1704|
        NOP      
        MOVS     r1,#0x11
        LDR      r3,|L0.2064|
        STR      r1,[r3,#0x20]
        POP      {r4,pc}
        ENDP

Touch_Config_Mode PROC
        PUSH     {r4,r5,lr}
        MOVS     r4,#0
        B        |L0.1734|
|L0.1720|
        MOVS     r1,#0
        LDR      r0,|L0.2064|
        SUBS     r0,r0,#0x40
        LSLS     r2,r4,#2
        STR      r1,[r0,r2]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.1734|
        CMP      r4,#0x18
        BLT      |L0.1720|
        LDR      r0,|L0.2064|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#4]
        MOVS     r1,#0x1c
        BICS     r0,r0,r1
        LDR      r1,|L0.2064|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#4]
        LDR      r0,|L0.2056|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0x11]  ; ts
        CMP      r0,#1
        BNE      |L0.2016|
        MOVS     r4,#0
        B        |L0.1818|
|L0.1768|
        LDR      r0,|L0.2056|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSRS     r0,r0,#7
        CMP      r0,#0
        BEQ      |L0.1792|
        LDR      r0,|L0.2056|
        LDR      r0,[r0,#0x50]  ; ts
        LDRB     r1,[r0,r4]
        LDR      r0,|L0.2064|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0x14]
|L0.1792|
        MOV      r0,r4
        BL       Touch_Get_Single_CH
        LDR      r0,|L0.2056|
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.2056|
        LDR      r1,[r1,#4]  ; ts
        LSLS     r2,r4,#2
        STR      r0,[r1,r2]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.1818|
        LDR      r0,|L0.2056|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.1768|
        MOVS     r4,#0
        B        |L0.1854|
|L0.1832|
        MOVS     r1,#1
        LSLS     r1,r1,#11
        LDR      r0,|L0.2064|
        SUBS     r0,r0,#0x40
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        STR      r1,[r0,r2]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.1854|
        LDR      r0,|L0.2056|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.1832|
        LDR      r0,|L0.2064|
        ADDS     r0,r0,#0x20
        LDR      r0,[r0,#4]
        MOVS     r1,#0xc
        ORRS     r0,r0,r1
        LDR      r1,|L0.2064|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#4]
        ASRS     r5,r1,#20
        NOP      
|L0.1884|
        MOVS     r4,#0
        B        |L0.1980|
|L0.1888|
        MOV      r0,r4
        BL       Touch_Get_Single_CH
        LDR      r0,|L0.2056|
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.2056|
        LDR      r1,[r1,#4]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BLS      |L0.1946|
        LDR      r0,|L0.2064|
        SUBS     r0,r0,#0x40
        LDR      r1,|L0.2056|
        LDR      r1,[r1,#0x4c]  ; ts
        LDRB     r1,[r1,r4]
        LSLS     r1,r1,#2
        LDR      r0,[r0,r1]
        ADDS     r1,r0,r5
        LDR      r0,|L0.2064|
        SUBS     r0,r0,#0x40
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        STR      r1,[r0,r2]
        B        |L0.1976|
|L0.1946|
        LDR      r0,|L0.2064|
        SUBS     r0,r0,#0x40
        LDR      r1,|L0.2056|
        LDR      r1,[r1,#0x4c]  ; ts
        LDRB     r1,[r1,r4]
        LSLS     r1,r1,#2
        LDR      r0,[r0,r1]
        SUBS     r1,r0,r5
        LDR      r0,|L0.2064|
        SUBS     r0,r0,#0x40
        LDR      r2,|L0.2056|
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        STR      r1,[r0,r2]
|L0.1976|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.1980|
        LDR      r0,|L0.2056|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.1888|
        LSRS     r5,r5,#1
        CMP      r5,#0
        BNE      |L0.1884|
        NOP      
        NOP      
        LDR      r0,|L0.2056|
        ADDS     r0,r0,#0x80
        LDR      r1,[r0,#0x2c]  ; ts
        LDR      r0,|L0.2064|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0x2c]
        LDR      r0,|L0.2056|
        B        |L0.2018|
|L0.2016|
        B        |L0.2088|
|L0.2018|
        ADDS     r0,r0,#0x80
        LDR      r1,[r0,#0x28]  ; ts
        LDR      r0,|L0.2064|
        ADDS     r0,r0,#0x20
        STR      r1,[r0,#0x30]
        LDR      r0,[r0,#4]
        MOVS     r1,#0x18
        BICS     r0,r0,r1
        LDR      r1,|L0.2064|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#4]
        MOV      r0,r1
        LDR      r0,[r0,#4]
        MOVS     r1,#4
        ORRS     r0,r0,r1
        LDR      r1,|L0.2064|
        ADDS     r1,r1,#0x20
        STR      r0,[r1,#4]
|L0.2054|
        B        |L0.2470|
|L0.2056|
        DCD      ||ts||
|L0.2060|
        DCD      key_channel_map
|L0.2064|
        DCD      0x40003700
|L0.2068|
        DCD      t_sysbit
|L0.2072|
        DCD      ts_reg+0x60
|L0.2076|
        DCD      0x40003600
|L0.2080|
        DCD      0xe000e280
|L0.2084|
        DCD      0xe000e100
|L0.2088|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#0x11]  ; ts
        CMP      r0,#2
        BNE      |L0.2054|
        MOVS     r1,#0
        LDR      r0,|L0.3096|
        STRB     r1,[r0,#0x12]
        MOVS     r4,#0
        B        |L0.2134|
|L0.2106|
        LDR      r0,|L0.3096|
        ADDS     r0,r0,#0x78
        LDRB     r0,[r0,#1]
        LSRS     r0,r0,#7
        CMP      r0,#0
        BEQ      |L0.2130|
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x50]  ; ts
        LDRB     r1,[r0,r4]
        LDR      r0,|L0.3100|
        STR      r1,[r0,#0x14]
|L0.2130|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.2134|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.2106|
        MOVS     r0,#0
        BL       Touch_Get_Single_CH
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LDR      r0,[r0,#0]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#4]  ; ts
        STR      r0,[r1,#0]
        MOVS     r4,#1
        B        |L0.2222|
|L0.2168|
        MOV      r0,r4
        BL       Touch_Get_Single_CH
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#4]  ; ts
        LDR      r1,[r1,#0]
        CMP      r0,r1
        BCS      |L0.2218|
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#4]  ; ts
        STR      r0,[r1,#0]
        LDR      r0,|L0.3096|
        STRB     r4,[r0,#0x12]
|L0.2218|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.2222|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.2168|
        LDR      r0,|L0.3100|
        LDR      r0,[r0,#4]
        MOVS     r1,#0x14
        BICS     r0,r0,r1
        LDR      r1,|L0.3100|
        STR      r0,[r1,#4]
        MOV      r0,r1
        LDR      r0,[r0,#4]
        MOVS     r1,#8
        ORRS     r0,r0,r1
        LDR      r1,|L0.3100|
        STR      r0,[r1,#4]
        LDR      r1,|L0.3096|
        LDRB     r0,[r1,#0x12]  ; ts
        BL       Touch_Get_Single_CH
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r1,[r0,#0x1c]  ; ts
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0x12]  ; ts
        LSLS     r0,r0,#3
        LDR      r0,[r1,r0]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#4]  ; ts
        STR      r0,[r1,#0]
        MOVS     r4,#0
        B        |L0.2320|
|L0.2288|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#0x12]  ; ts
        CMP      r0,r4
        BEQ      |L0.2316|
        MOVS     r1,#1
        LSLS     r1,r1,#11
        LDR      r0,|L0.3100|
        SUBS     r0,r0,#0x60
        LDR      r2,|L0.3096|
        SUBS     r2,r2,#0x60
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        STR      r1,[r0,r2]
|L0.2316|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.2320|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.2288|
        MOVS     r5,#1
        LSLS     r5,r5,#10
        NOP      
|L0.2334|
        MOVS     r4,#0
        B        |L0.2452|
|L0.2338|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#0x12]  ; ts
        CMP      r0,r4
        BNE      |L0.2348|
        B        |L0.2448|
|L0.2348|
        MOV      r0,r4
        BL       Touch_Get_Single_CH
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#4]  ; ts
        LDR      r1,[r1,#0]
        CMP      r0,r1
        BLS      |L0.2412|
        LDR      r0,|L0.3100|
        SUBS     r0,r0,#0x60
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x4c]  ; ts
        LDRB     r1,[r1,r4]
        LSLS     r1,r1,#2
        LDR      r0,[r0,r1]
        ADDS     r1,r0,r5
        LDR      r0,|L0.3100|
        SUBS     r0,r0,#0x60
        LDR      r2,|L0.3096|
        SUBS     r2,r2,#0x60
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        STR      r1,[r0,r2]
        B        |L0.2446|
|L0.2412|
        LDR      r0,|L0.3100|
        SUBS     r0,r0,#0x60
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x4c]  ; ts
        LDRB     r1,[r1,r4]
        LSLS     r1,r1,#2
        LDR      r0,[r0,r1]
        SUBS     r1,r0,r5
        LDR      r0,|L0.3100|
        SUBS     r0,r0,#0x60
        LDR      r2,|L0.3096|
        SUBS     r2,r2,#0x60
        LDR      r2,[r2,#0x4c]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        STR      r1,[r0,r2]
|L0.2446|
        NOP      
|L0.2448|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.2452|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.2338|
        LSRS     r5,r5,#1
        CMP      r5,#0
        BNE      |L0.2334|
        NOP      
        NOP      
|L0.2470|
        MOVS     r4,#0
        B        |L0.2492|
|L0.2474|
        LDR      r0,|L0.3100|
        SUBS     r0,r0,#0x60
        LSLS     r1,r4,#2
        LDR      r0,[r0,r1]
        LSLS     r1,r4,#2
        LDR      r2,|L0.3104|
        STR      r0,[r2,r1]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.2492|
        CMP      r4,#0x18
        BLT      |L0.2474|
        POP      {r4,r5,pc}
        ENDP

Touch_Init_Base PROC
        PUSH     {r4,lr}
        BL       UT_Get_Status
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.2764|
        MOVS     r0,#1
        BL       UT_Is_Expired
        CMP      r0,#1
        BNE      |L0.2766|
        MOVS     r4,#0
        B        |L0.2702|
|L0.2526|
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r1,[r0,r1]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        STR      r1,[r0,r2]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r1,[r0,#4]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        STR      r1,[r0,#4]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x30]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x30]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        MOVS     r0,#0
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0xc]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0xc]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x10]  ; ts
        STRB     r0,[r1,r4]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x14]  ; ts
        STRB     r0,[r1,r4]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.2702|
        LDR      r0,|L0.3096|
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.2526|
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x24]  ; ts
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BNE      |L0.2754|
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x20]  ; ts
        LDR      r0,[r0,#0]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x24]  ; ts
        STR      r0,[r1,#0]
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x20]  ; ts
        LDR      r0,[r0,#4]
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x24]  ; ts
        STR      r0,[r1,#4]
|L0.2754|
        LDR      r0,|L0.3096|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0x18]  ; ts
        LSRS     r0,r0,#1
        B        |L0.2768|
|L0.2764|
        B        |L0.2780|
|L0.2766|
        B        |L0.2792|
|L0.2768|
        LSLS     r0,r0,#1
        ADDS     r0,r0,#1
        LDR      r1,|L0.3096|
        ADDS     r1,r1,#0x60
        STRB     r0,[r1,#0x18]
        B        |L0.2792|
|L0.2780|
        LDR      r0,|L0.3096|
        ADDS     r0,r0,#0x20
        LDR      r1,[r0,#0]  ; ts
        MOVS     r0,#1
        BL       UT_Set_Timer
|L0.2792|
        POP      {r4,pc}
        ENDP

Touch_Update_Base PROC
        PUSH     {r3-r7,lr}
        BL       UT_Get_Status
        MOVS     r1,#4
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L0.3060|
        MOVS     r0,#4
        BL       UT_Is_Expired
        CMP      r0,#1
        BNE      |L0.3062|
        MOVS     r4,#0
        B        |L0.3184|
|L0.2822|
        MOVS     r5,#0
        B        |L0.3174|
|L0.2826|
        LDR      r2,|L0.3096|
        ADDS     r2,r2,#0x20
        LDR      r2,[r2,#0x18]  ; ts
        LSLS     r3,r4,#3
        ADDS     r2,r2,r3
        LSLS     r3,r5,#2
        LDR      r0,[r2,r3]
        LDR      r2,|L0.3096|
        ADDS     r2,r2,#0x20
        LDR      r1,[r2,#0x20]  ; ts
        BL       __aeabi_uidivmod
        LDR      r1,|L0.3096|
        ADDS     r1,r1,#0x20
        LDR      r1,[r1,#0x1c]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LSLS     r2,r5,#2
        STR      r0,[r1,r2]
        MOVS     r0,#1
        LSLS     r0,r0,r4
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x5c]  ; ts
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L0.3094|
        LDR      r0,|L0.3096|
        SUBS     r0,r0,#0x60
        LDR      r0,[r0,#0x44]  ; ts
        LDRB     r0,[r0,r4]
        CMP      r0,#0
        BNE      |L0.3140|
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.3096|
        ADDS     r2,r2,#0x40
        LDRB     r2,[r2,#5]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x3c]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BLE      |L0.3154|
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.3096|
        ADDS     r2,r2,#0x40
        LDRB     r2,[r2,#4]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x3c]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BLE      |L0.2982|
        LDR      r0,|L0.3096|
        ADDS     r0,r0,#0x20
        LDRB     r0,[r0,#0x11]  ; ts
        STR      r0,[sp,#0]
        B        |L0.2990|
|L0.2982|
        LDR      r0,|L0.3096|
        ADDS     r0,r0,#0x20
        LDRB     r0,[r0,#0x12]  ; ts
        STR      r0,[sp,#0]
|L0.2990|
        LDR      r1,|L0.3096|
        SUBS     r1,r1,#0x60
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LSLS     r2,r5,#2
        LDR      r1,[r1,r2]
        LDR      r2,[sp,#0]
        MULS     r1,r2,r1
        LDR      r2,|L0.3096|
        ADDS     r2,r2,#0x20
        LDR      r2,[r2,#0x1c]  ; ts
        LSLS     r3,r4,#3
        ADDS     r2,r2,r3
        LSLS     r3,r5,#2
        LDR      r2,[r2,r3]
        ADDS     r0,r1,r2
        LDR      r1,[sp,#0]
        ADDS     r1,r1,#1
        BL       __aeabi_uidivmod
        MOV      r6,r0
        LDR      r2,|L0.3096|
        SUBS     r2,r2,#0x60
        LDR      r2,[r2,#0x34]  ; ts
        LSLS     r3,r4,#3
        ADDS     r2,r2,r3
        LSLS     r3,r5,#2
        LDR      r2,[r2,r3]
        SUBS     r0,r6,r2
        LDR      r2,|L0.3096|
        SUBS     r2,r2,#0x60
        LDR      r2,[r2,#0x38]  ; ts
        LSLS     r3,r4,#3
        B        |L0.3064|
|L0.3060|
        B        |L0.3302|
|L0.3062|
        B        |L0.3214|
|L0.3064|
        ADDS     r2,r2,r3
        LSLS     r3,r5,#2
        LDR      r2,[r2,r3]
        LDR      r3,|L0.3096|
        SUBS     r3,r3,#0x60
        LDR      r3,[r3,#0x34]  ; ts
        LSLS     r7,r4,#3
        ADDS     r3,r3,r7
        LSLS     r7,r5,#2
        LDR      r3,[r3,r7]
        SUBS     r1,r2,r3
        CMP      r1,#0
        BLT      |L0.3110|
        MOV      r2,r1
        B        |L0.3112|
|L0.3094|
        B        |L0.3138|
|L0.3096|
        DCD      ||ts||+0x60
|L0.3100|
        DCD      0x40003720
|L0.3104|
        DCD      ts_reg
        B        |L0.3140|
|L0.3110|
        RSBS     r2,r1,#0
|L0.3112|
        CMP      r0,#0
        BLT      |L0.3120|
        MOV      r3,r0
        B        |L0.3122|
|L0.3120|
        RSBS     r3,r0,#0
|L0.3122|
        CMP      r2,r3
        BLE      |L0.3154|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x38]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LSLS     r1,r5,#2
        STR      r6,[r0,r1]
|L0.3138|
        B        |L0.3154|
|L0.3140|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x44]  ; ts
        LDRB     r0,[r0,r4]
        SUBS     r0,r0,#1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x44]  ; ts
        STRB     r0,[r1,r4]
|L0.3154|
        MOVS     r1,#0
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        LSLS     r2,r5,#2
        STR      r1,[r0,r2]
        ADDS     r0,r5,#1
        UXTB     r5,r0
|L0.3174|
        CMP      r5,#2
        BGE      |L0.3180|
        B        |L0.2826|
|L0.3180|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.3184|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BLE      |L0.3196|
        B        |L0.2822|
|L0.3196|
        MOVS     r1,#0
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        STR      r1,[r0,#0x20]  ; ts
        LDR      r1,[r0,#0x14]  ; ts
        MOVS     r0,#4
        BL       UT_Set_Timer
        B        |L0.3364|
|L0.3214|
        MOVS     r4,#0
        B        |L0.3276|
|L0.3218|
        MOVS     r5,#0
        B        |L0.3268|
|L0.3222|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LSLS     r1,r5,#2
        LDR      r0,[r0,r1]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LSLS     r2,r5,#2
        LDR      r1,[r1,r2]
        ADDS     r1,r0,r1
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        LSLS     r2,r5,#2
        STR      r1,[r0,r2]
        ADDS     r0,r5,#1
        UXTB     r5,r0
|L0.3268|
        CMP      r5,#2
        BLT      |L0.3222|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.3276|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.3218|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x20]  ; ts
        ADDS     r0,r0,#1
        LDR      r1,|L0.4144|
        ADDS     r1,r1,#0x80
        STR      r0,[r1,#0x20]  ; ts
        B        |L0.3364|
|L0.3302|
        MOVS     r4,#0
        B        |L0.3338|
|L0.3306|
        MOVS     r5,#0
        B        |L0.3330|
|L0.3310|
        MOVS     r1,#0
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        LSLS     r2,r5,#2
        STR      r1,[r0,r2]
        ADDS     r0,r5,#1
        UXTB     r5,r0
|L0.3330|
        CMP      r5,#2
        BLT      |L0.3310|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.3338|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.3306|
        MOVS     r1,#0
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        STR      r1,[r0,#0x20]  ; ts
        LDR      r1,[r0,#0x14]  ; ts
        MOVS     r0,#4
        BL       UT_Set_Timer
|L0.3364|
        POP      {r3-r7,pc}
        ENDP

Touch_Ref_Compen PROC
        PUSH     {r4,lr}
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x6c]  ; ts
        CMP      r0,#0
        BNE      |L0.3432|
        MOVS     r4,#0
        B        |L0.3420|
|L0.3380|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x28]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r1,[r0,#4]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x28]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        STR      r1,[r0,#4]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.3420|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.3380|
        B        |L0.3550|
|L0.3432|
        MOVS     r4,#0
        B        |L0.3540|
|L0.3436|
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x24]  ; ts
        LDR      r1,[r1,#0]
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0x20]  ; ts
        LDR      r2,[r2,#0]
        SUBS     r1,r1,r2
        LSLS     r2,r4,#2
        LDR      r3,|L0.4148|
        LDR      r2,[r3,r2]
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x1c]  ; ts
        LSLS     r2,r4,#3
        LDR      r1,[r1,r2]
        ADDS     r0,r0,r1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x28]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x24]  ; ts
        LDR      r1,[r1,#4]
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0x20]  ; ts
        LDR      r2,[r2,#4]
        SUBS     r1,r1,r2
        LSLS     r2,r4,#2
        LDR      r3,|L0.4148|
        LDR      r2,[r3,r2]
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x1c]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        ADDS     r0,r0,r1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x28]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.3540|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.3436|
|L0.3550|
        POP      {r4,pc}
        ENDP

Touch_Make_Data PROC
        PUSH     {r2-r6,lr}
        MOVS     r4,#0
        B        |L0.4052|
|L0.3558|
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0x30]  ; ts
        LSLS     r3,r4,#3
        LDR      r2,[r2,r3]
        LDR      r3,|L0.4144|
        ADDS     r3,r3,#0x60
        LDRB     r3,[r3,#0x15]  ; ts
        MULS     r2,r3,r2
        LDR      r3,|L0.4144|
        LDR      r3,[r3,#0x2c]  ; ts
        LSLS     r5,r4,#3
        LDR      r3,[r3,r5]
        ADDS     r0,r2,r3
        LDR      r2,|L0.4144|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x15]  ; ts
        ADDS     r1,r2,#1
        BL       __aeabi_uidivmod
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0x30]  ; ts
        LSLS     r3,r4,#3
        ADDS     r2,r2,r3
        LDR      r2,[r2,#4]
        LDR      r3,|L0.4144|
        ADDS     r3,r3,#0x60
        LDRB     r3,[r3,#0x15]  ; ts
        MULS     r2,r3,r2
        LDR      r3,|L0.4144|
        LDR      r3,[r3,#0x2c]  ; ts
        LSLS     r5,r4,#3
        ADDS     r3,r3,r5
        LDR      r3,[r3,#4]
        ADDS     r0,r2,r3
        LDR      r2,|L0.4144|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x15]  ; ts
        ADDS     r1,r2,#1
        BL       __aeabi_uidivmod
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r4,#3
        LDR      r1,[r0,r1]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        LDR      r0,[r0,r2]
        SUBS     r0,r1,r0
        STR      r0,[sp,#0]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x18]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        SUBS     r0,r0,r1
        STR      r0,[sp,#4]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0xc]  ; ts
        LSLS     r2,r4,#3
        LDR      r2,[r1,r2]
        LDR      r0,[sp,#0]
        CMP      r0,#0
        BLT      |L0.3718|
        MOV      r1,r0
        B        |L0.3720|
|L0.3718|
        RSBS     r1,r0,#0
|L0.3720|
        ADDS     r1,r2,r1
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0xc]  ; ts
        LSLS     r3,r4,#3
        STR      r1,[r2,r3]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0xc]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r2,[r1,#4]
        LDR      r0,[sp,#4]
        CMP      r0,#0
        BLT      |L0.3750|
        MOV      r1,r0
        B        |L0.3752|
|L0.3750|
        RSBS     r1,r0,#0
|L0.3752|
        ADDS     r1,r2,r1
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0xc]  ; ts
        LSLS     r3,r4,#3
        ADDS     r2,r2,r3
        STR      r1,[r2,#4]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x10]  ; ts
        LDRB     r0,[r0,r4]
        ADDS     r0,r0,#1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x10]  ; ts
        STRB     r0,[r1,r4]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x10]  ; ts
        LDRB     r0,[r1,r4]
        MOVS     r1,#5
        BL       __aeabi_idivmod
        UXTB     r0,r1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x10]  ; ts
        STRB     r0,[r1,r4]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x10]  ; ts
        LDRB     r0,[r0,r4]
        CMP      r0,#0
        BNE      |L0.3928|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0xc]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0xc]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        CMP      r0,r1
        BCS      |L0.3866|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x38]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        LDR      r1,[r1,r2]
        SUBS     r0,r0,r1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x3c]  ; ts
        LSLS     r2,r4,#2
        STR      r0,[r1,r2]
        MOVS     r0,#0
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x14]  ; ts
        STRB     r0,[r1,r4]
        B        |L0.3904|
|L0.3866|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x38]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r1,[r0,#4]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        LDR      r0,[r0,#4]
        SUBS     r0,r1,r0
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x3c]  ; ts
        LSLS     r2,r4,#2
        STR      r0,[r1,r2]
        MOVS     r0,#1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x14]  ; ts
        STRB     r0,[r1,r4]
|L0.3904|
        MOVS     r0,#0
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0xc]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        MOVS     r1,#0
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0xc]  ; ts
        LSLS     r2,r4,#3
        ADDS     r0,r0,r2
        STR      r1,[r0,#4]
        B        |L0.3974|
|L0.3928|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x38]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x14]  ; ts
        LDRB     r1,[r1,r4]
        LSLS     r1,r1,#2
        LDR      r0,[r0,r1]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r2,|L0.4144|
        LDR      r2,[r2,#0x14]  ; ts
        LDRB     r2,[r2,r4]
        LSLS     r2,r2,#2
        LDR      r1,[r1,r2]
        SUBS     r1,r0,r1
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x3c]  ; ts
        LSLS     r2,r4,#2
        STR      r1,[r0,r2]
|L0.3974|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        LDR      r1,[r0,r1]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r4,#3
        STR      r1,[r0,r2]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x1c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x18]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x2c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x30]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x2c]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x30]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.4052|
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BLE      |L0.4064|
        B        |L0.3558|
|L0.4064|
        POP      {r2-r6,pc}
        ENDP

Touch_Disicion_Key PROC
        PUSH     {r3-r7,lr}
        MOVS     r1,#0
        LDR      r0,|L0.4144|
        ADDS     r0,r0,#0x80
        STR      r1,[r0,#0x54]  ; ts
        MOVS     r4,#0
        B        |L0.5104|
|L0.4080|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x5c]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L0.4348|
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.4144|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x1d]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x40]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BLE      |L0.4220|
        LDR      r0,|L0.4144|
        LDR      r0,[r0,#0x48]  ; ts
        LDRB     r0,[r0,r4]
        SUBS     r0,r0,#1
        LDR      r1,|L0.4144|
        LDR      r1,[r1,#0x48]  ; ts
        B        |L0.4152|
|L0.4144|
        DCD      ||ts||
|L0.4148|
        DCD      ref_channel_gain
|L0.4152|
        STRB     r0,[r1,r4]
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x48]  ; ts
        LDRB     r0,[r0,r4]
        CMP      r0,#0
        BNE      |L0.4198|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x5c]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x5c]  ; ts
        MOV      r0,r1
        LDR      r0,[r0,#0x58]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x58]  ; ts
        MOVS     r0,#3
        LDR      r1,[r1,#0x44]  ; ts
        STRB     r0,[r1,r4]
|L0.4198|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#29
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.4312|
        MOVS     r0,#8
        BL       UT_Clear_Timer
        B        |L0.4312|
|L0.4220|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0x14]  ; ts
        ADDS     r0,r0,#1
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x48]  ; ts
        STRB     r0,[r1,r4]
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#29
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.4312|
        MOVS     r0,#8
        BL       UT_Is_Expired
        CMP      r0,#1
        BNE      |L0.4312|
        MOVS     r4,#0
        B        |L0.4302|
|L0.4262|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        STR      r0,[r1,r2]
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r4,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.4302|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.4262|
|L0.4312|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#27
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.4360|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x40]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L0.4360|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        B        |L0.4350|
|L0.4348|
        B        |L0.4362|
|L0.4350|
        LDR      r0,[r0,#0x54]  ; ts
        ADDS     r0,r0,#1
        LDR      r1,|L0.5172|
        ADDS     r1,r1,#0x80
        STR      r0,[r1,#0x54]  ; ts
|L0.4360|
        B        |L0.4658|
|L0.4362|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x40]  ; ts
        LSLS     r1,r4,#2
        LDR      r0,[r0,r1]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BLE      |L0.4636|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x48]  ; ts
        LDRB     r0,[r0,r4]
        ADDS     r0,r0,#1
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x48]  ; ts
        STRB     r0,[r1,r4]
        MOVS     r0,#3
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x44]  ; ts
        STRB     r0,[r1,r4]
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x48]  ; ts
        LDRB     r1,[r0,r4]
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0x13]  ; ts
        CMP      r1,r0
        BLE      |L0.4658|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#29
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.4454|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x5c]  ; ts
        CMP      r0,#0
        BNE      |L0.4454|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r1,[r0,#0x38]  ; ts
        MOVS     r0,#8
        BL       UT_Set_Timer
|L0.4454|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#0x14]  ; ts
        ADDS     r0,r0,#1
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x48]  ; ts
        STRB     r0,[r1,r4]
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x5c]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ORRS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x5c]  ; ts
        MOV      r0,r1
        LDR      r0,[r0,#0x58]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ORRS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x58]  ; ts
        MOV      r0,r1
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#26
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.4560|
        MOV      r0,r1
        LDR      r0,[r0,#0x3c]  ; ts
        LSLS     r1,r4,#2
        LDR      r1,[r0,r1]
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x48]  ; ts
        LSLS     r2,r4,#2
        LDR      r0,[r0,r2]
        CMP      r1,r0
        BLE      |L0.4560|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x5c]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x5c]  ; ts
        MOV      r0,r1
        LDR      r0,[r0,#0x58]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x58]  ; ts
|L0.4560|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#25
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.4658|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x10]  ; ts
        CMP      r0,#0
        BNE      |L0.4600|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x4c]  ; ts
        LDRB     r1,[r0,r4]
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xc0
        STRB     r1,[r0,#0x10]
        B        |L0.4658|
|L0.4600|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xc0
        LDRB     r1,[r0,#0x10]  ; ts
        SUBS     r0,r0,#0x40
        LDR      r0,[r0,#0x4c]  ; ts
        LDRB     r0,[r0,r4]
        CMP      r1,r0
        BEQ      |L0.4658|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x5c]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x5c]  ; ts
        MOV      r0,r1
        LDR      r0,[r0,#0x58]  ; ts
        B        |L0.4638|
|L0.4636|
        B        |L0.4650|
|L0.4638|
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x58]  ; ts
        B        |L0.4658|
|L0.4650|
        MOVS     r0,#0
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x48]  ; ts
        STRB     r0,[r1,r4]
|L0.4658|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.5172|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x1c]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        LDR      r1,[r1,r2]
        LDR      r2,|L0.5172|
        LDR      r2,[r2,#0x34]  ; ts
        LSLS     r3,r4,#3
        LDR      r2,[r2,r3]
        SUBS     r7,r1,r2
        CMP      r7,#0
        BLT      |L0.4712|
        MOV      r1,r7
        B        |L0.4714|
|L0.4712|
        RSBS     r1,r7,#0
|L0.4714|
        CMP      r0,r1
        BCC      |L0.4778|
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.5172|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x1c]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        LDR      r2,|L0.5172|
        LDR      r2,[r2,#0x34]  ; ts
        LSLS     r3,r4,#3
        ADDS     r2,r2,r3
        LDR      r2,[r2,#4]
        SUBS     r6,r1,r2
        CMP      r6,#0
        BLT      |L0.4772|
        MOV      r1,r6
        B        |L0.4774|
|L0.4772|
        RSBS     r1,r6,#0
|L0.4774|
        CMP      r0,r1
        BCS      |L0.4782|
|L0.4778|
        MOVS     r0,#1
        STR      r0,[sp,#0]
|L0.4782|
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.5172|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x1c]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        LDR      r1,[r1,r2]
        ADDS     r0,r0,r1
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BCC      |L0.4878|
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#8]  ; ts
        LSLS     r2,r4,#2
        LDR      r1,[r1,r2]
        LDR      r2,|L0.5172|
        ADDS     r2,r2,#0x60
        LDRB     r2,[r2,#0x1c]  ; ts
        MULS     r1,r2,r1
        MOV      r0,r1
        MOVS     r1,#0x64
        BL       __aeabi_idivmod
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        ADDS     r0,r0,r1
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x34]  ; ts
        LSLS     r2,r4,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        CMP      r0,r1
        BCS      |L0.4882|
|L0.4878|
        MOVS     r0,#1
        STR      r0,[sp,#0]
|L0.4882|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x5c]  ; ts
        CMP      r0,#0
        BNE      |L0.4900|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x48]  ; ts
        LDRB     r0,[r0,r4]
        CMP      r0,#0
        BEQ      |L0.4910|
|L0.4900|
        MOVS     r1,#0xff
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        STRB     r1,[r0,#4]
        B        |L0.5100|
|L0.4910|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDRB     r0,[r0,#4]  ; ts
        CMP      r0,#0xff
        BNE      |L0.4974|
        LDR      r0,[sp,#0]
        CMP      r0,#1
        BNE      |L0.5100|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        STRB     r4,[r0,#4]
        SUBS     r0,r0,#0x80
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r4,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r4,#3
        LDR      r1,[r1,r2]
        CMP      r0,r1
        BLS      |L0.4962|
        MOVS     r1,#0x64
        MOVS     r0,#2
        BL       UT_Set_Timer
        B        |L0.5100|
|L0.4962|
        LDR      r0,|L0.5172|
        LDR      r1,[r0,#0x78]  ; ts
        MOVS     r0,#2
        BL       UT_Set_Timer
        B        |L0.5100|
|L0.4974|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDRB     r0,[r0,#4]  ; ts
        CMP      r0,r4
        BNE      |L0.5100|
        LDR      r0,[sp,#0]
        CMP      r0,#1
        BNE      |L0.5086|
        MOVS     r0,#2
        BL       UT_Is_Expired
        CMP      r0,#1
        BNE      |L0.5100|
        MOVS     r5,#0
        B        |L0.5074|
|L0.5004|
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r5,#3
        LDR      r0,[r0,r1]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r5,#3
        STR      r0,[r1,r2]
        LDR      r0,|L0.5172|
        LDR      r0,[r0,#0x34]  ; ts
        LSLS     r1,r5,#3
        ADDS     r0,r0,r1
        LDR      r0,[r0,#4]
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x38]  ; ts
        LSLS     r2,r5,#3
        ADDS     r1,r1,r2
        STR      r0,[r1,#4]
        MOVS     r1,#0
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r5,#3
        STR      r1,[r0,r2]
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x18]  ; ts
        LSLS     r2,r5,#3
        ADDS     r0,r0,r2
        STR      r1,[r0,#4]
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        STR      r1,[r0,#0x20]  ; ts
        ADDS     r0,r5,#1
        UXTB     r5,r0
|L0.5074|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r5
        BGT      |L0.5004|
        B        |L0.5100|
|L0.5086|
        MOVS     r1,#0xff
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        STRB     r1,[r0,#4]
        MOVS     r0,#2
        BL       UT_Clear_Timer
|L0.5100|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.5104|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BLE      |L0.5116|
        B        |L0.4080|
|L0.5116|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#28
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5184|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x3c]  ; ts
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x5c]  ; ts
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L0.5184|
        LDR      r0,|L0.5172|
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x3c]  ; ts
        LDR      r1,|L0.5172|
        LDR      r1,[r1,#0x5c]  ; ts
        ANDS     r0,r0,r1
        LDR      r1,|L0.5172|
        STR      r0,[r1,#0x5c]  ; ts
        MOV      r0,r1
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x3c]  ; ts
        LDR      r1,[r1,#0x5c]  ; ts
        B        |L0.5176|
|L0.5172|
        DCD      ||ts||
|L0.5176|
        ANDS     r0,r0,r1
        LDR      r1,|L0.5856|
        STR      r0,[r1,#0x58]  ; ts
|L0.5182|
        POP      {r3-r7,pc}
|L0.5184|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#25
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5214|
        LDR      r0,|L0.5856|
        LDR      r0,[r0,#0x5c]  ; ts
        CMP      r0,#0
        BNE      |L0.5214|
        MOVS     r1,#0
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        STRB     r1,[r0,#0x10]
|L0.5214|
        MOVS     r1,#0
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0x80
        STRB     r1,[r0,#0x10]
        MOVS     r4,#0
        B        |L0.5256|
|L0.5226|
        LDR      r0,|L0.5856|
        LDR      r0,[r0,#0x5c]  ; ts
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L0.5252|
        ADDS     r0,r4,#1
        UXTB     r1,r0
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0x80
        STRB     r1,[r0,#0x10]
        B        |L0.5266|
|L0.5252|
        ADDS     r0,r4,#1
        UXTB     r4,r0
|L0.5256|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0x60
        LDRB     r0,[r0,#1]  ; ts
        CMP      r0,r4
        BGT      |L0.5226|
|L0.5266|
        NOP      
        NOP      
        B        |L0.5182|
        ENDP

Touch_Do_Task PROC
        PUSH     {r4,lr}
        LDR      r0,|L0.5856|
        LDRB     r0,[r0,#0]  ; ts
        MOVS     r3,r0
        BL       __ARM_common_switch8
        DCB      0x08,0x05,0x0d,0x2f
        DCB      0x54,0x86,0x9e,0xe3
        DCB      0xf8,0xf7
        BL       Touch_Init_Variable
        BL       Touch_Init_Register
        MOVS     r0,#1
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5850|
        LDR      r0,|L0.5860|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#27
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5336|
        LDR      r0,|L0.5860|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#25
        LSRS     r0,r0,#31
        CMP      r0,#0
        BNE      |L0.5336|
        B        |L0.5850|
|L0.5336|
        BL       Touch_Config_Mode
        LDR      r0,|L0.5860|
        LDR      r0,[r0,#0]  ; t_sysbit
        MOVS     r1,#2
        BICS     r0,r0,r1
        ADDS     r0,r0,#2
        LDR      r1,|L0.5860|
        STR      r0,[r1,#0]  ; t_sysbit
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#6
        BICS     r0,r0,r1
        LDR      r1,|L0.5856|
        ADDS     r1,r1,#0xc0
        STRB     r0,[r1,#0x18]
        MOVS     r0,#2
        SUBS     r1,r1,#0xc0
        STRB     r0,[r1,#0]
        B        |L0.5850|
        LDR      r0,|L0.5860|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#27
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5402|
        LDR      r0,|L0.5860|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#24
        LSRS     r0,r0,#31
        CMP      r0,#0
        BNE      |L0.5420|
|L0.5402|
        LDR      r1,|L0.5856|
        ADDS     r1,r1,#0x60
        LDRB     r0,[r1,#0]  ; ts
        BL       Touch_Start_Touch
        MOVS     r0,#3
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5450|
|L0.5420|
        LDR      r0,|L0.5860|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#27
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5450|
        LDR      r0,|L0.5860|
        LDRB     r0,[r0,#0]  ; t_sysbit
        LSLS     r0,r0,#29
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5450|
        MOVS     r0,#3
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
|L0.5450|
        B        |L0.5850|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        LSLS     r0,r0,#29
        LSRS     r0,r0,#30
        CMP      r0,#1
        BNE      |L0.5502|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#6
        BICS     r0,r0,r1
        LDR      r1,|L0.5856|
        ADDS     r1,r1,#0xc0
        STRB     r0,[r1,#0x18]
        LDR      r0,|L0.5860|
        LDR      r0,[r0,#0]  ; t_sysbit
        MOVS     r1,#4
        BICS     r0,r0,r1
        LDR      r1,|L0.5860|
        STR      r0,[r1,#0]  ; t_sysbit
        MOVS     r0,#2
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5550|
|L0.5502|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        LSLS     r0,r0,#29
        LSRS     r0,r0,#30
        CMP      r0,#2
        BNE      |L0.5550|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        MOVS     r1,#6
        BICS     r0,r0,r1
        LDR      r1,|L0.5856|
        ADDS     r1,r1,#0xc0
        STRB     r0,[r1,#0x18]
        LDR      r0,|L0.5860|
        LDR      r0,[r0,#0]  ; t_sysbit
        MOVS     r1,#4
        BICS     r0,r0,r1
        LDR      r1,|L0.5860|
        STR      r0,[r1,#0]  ; t_sysbit
        MOVS     r0,#4
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
|L0.5550|
        B        |L0.5850|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BNE      |L0.5592|
        BL       Touch_Init_Base
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xc0
        LDRB     r0,[r0,#0x18]  ; ts
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BNE      |L0.5598|
        MOVS     r0,#2
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5598|
|L0.5592|
        MOVS     r0,#5
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
|L0.5598|
        B        |L0.5850|
        BL       Touch_Ref_Compen
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#2]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5626|
        LDR      r0,|L0.5864|
        LDR      r0,[r0,#0]  ; func_p_user_filter_onesensingdata
        BLX      r0
        B        |L0.5682|
|L0.5626|
        MOVS     r0,#0
        B        |L0.5670|
|L0.5630|
        LDR      r1,|L0.5856|
        LDR      r1,[r1,#0x28]  ; ts
        LSLS     r2,r0,#3
        LDR      r1,[r1,r2]
        LDR      r2,|L0.5856|
        LDR      r2,[r2,#0x2c]  ; ts
        LSLS     r3,r0,#3
        STR      r1,[r2,r3]
        LDR      r1,|L0.5856|
        LDR      r1,[r1,#0x28]  ; ts
        LSLS     r2,r0,#3
        ADDS     r1,r1,r2
        LDR      r1,[r1,#4]
        LDR      r2,|L0.5856|
        LDR      r2,[r2,#0x2c]  ; ts
        LSLS     r3,r0,#3
        ADDS     r2,r2,r3
        STR      r1,[r2,#4]
        ADDS     r1,r0,#1
        UXTB     r0,r1
|L0.5670|
        LDR      r1,|L0.5856|
        ADDS     r1,r1,#0x60
        LDRB     r1,[r1,#1]  ; ts
        CMP      r1,r0
        BGT      |L0.5630|
        NOP      
|L0.5682|
        BL       Touch_Make_Data
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#2]
        LSLS     r0,r0,#30
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5708|
        LDR      r0,|L0.5868|
        LDR      r0,[r0,#0]  ; func_p_user_filter_diffdata
        BLX      r0
        B        |L0.5716|
|L0.5708|
        LDR      r0,|L0.5856|
        LDR      r0,[r0,#0x3c]  ; ts
        LDR      r1,|L0.5856|
        STR      r0,[r1,#0x40]  ; ts
|L0.5716|
        LDR      r0,|L0.5860|
        LDR      r0,[r0,#0]  ; t_sysbit
        MOVS     r1,#8
        BICS     r0,r0,r1
        ADDS     r0,r0,#8
        LDR      r1,|L0.5860|
        STR      r0,[r1,#0]  ; t_sysbit
        MOVS     r0,#6
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5850|
        BL       Touch_Disicion_Key
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#27
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5790|
        LDR      r0,|L0.5856|
        ADDS     r0,r0,#0x80
        LDR      r1,[r0,#0x54]  ; ts
        ADDS     r0,r0,#0x40
        LDRB     r0,[r0,#4]  ; ts
        CMP      r1,r0
        BCC      |L0.5782|
        MOVS     r0,#8
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5796|
        B        |L0.5810|
        B        |L0.5798|
|L0.5782|
        MOVS     r0,#7
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5796|
|L0.5790|
        MOVS     r0,#7
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
|L0.5796|
        B        |L0.5850|
|L0.5798|
        BL       Touch_Update_Base
        MOVS     r0,#2
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        B        |L0.5850|
|L0.5810|
        MOVS     r0,#0
        LDR      r1,|L0.5856|
        STRB     r0,[r1,#0]
        MOV      r0,r1
        ADDS     r0,r0,#0xd8
        LDRB     r0,[r0,#1]
        LSLS     r0,r0,#27
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L0.5848|
        MOV      r0,r1
        ADDS     r0,r0,#0x80
        LDR      r0,[r0,#0x34]  ; ts
        ADDS     r0,r0,#1
        ADDS     r1,r1,#0x80
        STR      r0,[r1,#0x34]  ; ts
        MOVS     r0,#0x1d
        BL       __NVIC_DisableIRQ
|L0.5848|
        NOP      
|L0.5850|
        NOP      
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L0.5856|
        DCD      ||ts||
|L0.5860|
        DCD      t_sysbit
|L0.5864|
        DCD      func_p_user_filter_onesensingdata
|L0.5868|
        DCD      func_p_user_filter_diffdata

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

||ts||
        %        220
ts_reg
        %        172

        AREA ||.data||, DATA, ALIGN=2

func_p_user_filter_onesensingdata
        DCD      0x00000000
func_p_user_filter_diffdata
        DCD      0x00000000
key_channel_map
        DCD      0x00000002
        DCD      0x00000010
        DCD      0x00000080
        DCD      0x00000400
        DCD      0x00002000
        DCD      0x00010000
        DCD      0x00080000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000000
ref_channel_gain
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064
        DCD      0x00000064

        AREA ||i.__ARM_common_switch8||, COMGROUP=__ARM_common_switch8, CODE, READONLY, ALIGN=1

__ARM_common_switch8 PROC
        PUSH     {r4,r5}
        MOV      r4,lr
        SUBS     r4,r4,#1
        LDRB     r5,[r4,#0]
        ADDS     r4,r4,#1
        CMP      r3,r5
        BCC      |L15.24|
|L15.14|
        LDRB     r3,[r4,r5]
        LSLS     r3,r3,#1
        ADDS     r3,r4,r3
        POP      {r4,r5}
        BX       r3
|L15.24|
        MOV      r5,r3
        B        |L15.14|
        ENDP


;*** Start embedded assembler ***

#line 1 "..\\..\\code_lib\\touch.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___7_touch_c_95667e3c____REV16|
#line 492 "..\\..\\..\\..\\..\\core\\cmsis\\include\\cmsis_armcc.h"
|__asm___7_touch_c_95667e3c____REV16| PROC
#line 493

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___7_touch_c_95667e3c____REVSH|
#line 507
|__asm___7_touch_c_95667e3c____REVSH| PROC
#line 508

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT TOUCH_IRQHandler [CODE]
        EXPORT Touch_Set_Mode [CODE]
        EXPORT Touch_Set_Shield [CODE]
        EXPORT Touch_Set_Sum_Count [CODE]
        EXPORT Touch_Set_Common_THD [CODE]
        EXPORT Touch_Set_CH_THD [CODE]
        EXPORT Touch_Set_Common_POS_noise_THD [CODE]
        EXPORT Touch_Set_CH_POS_noise_THD [CODE]
        EXPORT Touch_Set_Group_CH [CODE]
        EXPORT Touch_Set_NoiseTHD_Rate [CODE]
        EXPORT Touch_Set_BaseHold_Rate [CODE]
        EXPORT Touch_Set_Base_Tracking [CODE]
        EXPORT Touch_Set_Hold_Key_Release_Time [CODE]
        EXPORT Touch_Set_Single_Key_Press_limit [CODE]
        EXPORT Touch_Set_Release_Rate [CODE]
        EXPORT Touch_Set_Reverse_Rate [CODE]
        EXPORT Touch_Set_Reverse_Time [CODE]
        EXPORT Touch_Set_Debounce [CODE]
        EXPORT Touch_Set_IIR [CODE]
        EXPORT Touch_Set_Init_Delay [CODE]
        EXPORT Touch_Set_Inact_Port [CODE]
        EXPORT Touch_Set_Frequency [CODE]
        EXPORT Touch_Set_Comp_RefV [CODE]
        EXPORT Touch_Set_VHS [CODE]
        EXPORT Touch_Set_Freq_Shift [CODE]
        EXPORT Touch_Set_Common_Serial_Register [CODE]
        EXPORT Touch_Set_CH_Serial_Register [CODE]
        EXPORT Touch_Get_Key [CODE]
        EXPORT Touch_Init_Variable [CODE]
        EXPORT Touch_Init_Register [CODE]
        EXPORT Touch_Get_Single_CH [CODE]
        EXPORT Touch_Start_Touch [CODE]
        EXPORT Touch_Config_Mode [CODE]
        EXPORT Touch_Init_Base [CODE]
        EXPORT Touch_Update_Base [CODE]
        EXPORT Touch_Ref_Compen [CODE]
        EXPORT Touch_Make_Data [CODE]
        EXPORT Touch_Disicion_Key [CODE]
        EXPORT Touch_Do_Task [CODE]
        EXPORT ||ts|| [DATA,SIZE=220]
        EXPORT ts_reg [DATA,SIZE=172]
        EXPORT func_p_user_filter_onesensingdata [DATA,SIZE=4]
        EXPORT func_p_user_filter_diffdata [DATA,SIZE=4]
        EXPORT key_channel_map [DATA,SIZE=96]
        EXPORT ref_channel_gain [DATA,SIZE=96]
        EXPORT __ARM_common_switch8 [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT t_sysbit [DATA]
        IMPORT HAL_GPIO_SetFunction [CODE]
        IMPORT HAL_GPIO_SetMode [CODE]
        IMPORT __aeabi_uidivmod [CODE]
        IMPORT UT_Get_Status [CODE]
        IMPORT UT_Is_Expired [CODE]
        IMPORT UT_Set_Timer [CODE]
        IMPORT __aeabi_idivmod [CODE]
        IMPORT UT_Clear_Timer [CODE]

        KEEP __NVIC_DisableIRQ

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
