; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --debug -c -S -o.\objects\user_timer.s --depend=.\objects\user_timer.d --cpu=Cortex-M0+ --apcs=interwork -O0 --diag_suppress=9931 -I..\..\..\..\..\core\device\a31t21x\include -I..\..\..\..\..\driver\a31t21x\include -I..\..\code_app\library\header -I..\..\common -I..\..\..\..\..\core\cmsis\include -I..\..\code_app -I.\RTE\_A31T21X -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\Device\ARM\ARMCM0plus\Include -IC:\Keil_v5\ARM\CMSIS\Include -D__UVISION_VERSION=526 -DARMCM0P --omf_browse=.\objects\user_timer.crf ..\..\code_lib\user_timer.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

UT_Run_Timer PROC
        MOVS     r0,#0
        LDR      r1,|L0.772|
        STR      r0,[r1,#0]  ; ut_timer_1
        LDR      r1,|L0.776|
        STR      r0,[r1,#0]  ; ut_timer_2
        LDR      r1,|L0.780|
        STR      r0,[r1,#0]  ; ut_timer_3
        LDR      r1,|L0.784|
        STR      r0,[r1,#0]  ; ut_timer_4
        LDR      r1,|L0.788|
        STR      r0,[r1,#0]  ; ut_timer_5
        LDR      r1,|L0.792|
        STR      r0,[r1,#0]  ; ut_timer_6
        LDR      r1,|L0.796|
        STR      r0,[r1,#0]  ; ut_timer_7
        LDR      r1,|L0.800|
        STR      r0,[r1,#0]  ; ut_timer_8
        LDR      r1,|L0.804|
        STR      r0,[r1,#0]  ; ut_set_flag
        LDR      r1,|L0.808|
        STR      r0,[r1,#0]  ; ut_expire_flag
        BX       lr
        ENDP

SysTick_Handler PROC
        LDR      r0,|L0.812|
        LDR      r0,[r0,#0]  ; ut_tick
        ADDS     r0,r0,#1
        LDR      r1,|L0.812|
        STR      r0,[r1,#0]  ; ut_tick
        BX       lr
        ENDP

UT_Set_Timer PROC
        PUSH     {r4,lr}
        MOV      r2,r0
        LDR      r3,|L0.812|
        LDR      r0,[r3,#0]  ; ut_tick
        CMP      r2,#0x10
        BEQ      |L0.134|
        BGT      |L0.88|
        CMP      r2,#1
        BEQ      |L0.102|
        CMP      r2,#2
        BEQ      |L0.110|
        CMP      r2,#4
        BEQ      |L0.118|
        CMP      r2,#8
        BNE      |L0.166|
        B        |L0.126|
|L0.88|
        CMP      r2,#0x20
        BEQ      |L0.142|
        CMP      r2,#0x40
        BEQ      |L0.150|
        CMP      r2,#0x80
        BNE      |L0.166|
        B        |L0.158|
|L0.102|
        ADDS     r3,r0,r1
        LDR      r4,|L0.772|
        STR      r3,[r4,#0]  ; ut_timer_1
        B        |L0.168|
|L0.110|
        ADDS     r3,r0,r1
        LDR      r4,|L0.776|
        STR      r3,[r4,#0]  ; ut_timer_2
        B        |L0.168|
|L0.118|
        ADDS     r3,r0,r1
        LDR      r4,|L0.780|
        STR      r3,[r4,#0]  ; ut_timer_3
        B        |L0.168|
|L0.126|
        ADDS     r3,r0,r1
        LDR      r4,|L0.784|
        STR      r3,[r4,#0]  ; ut_timer_4
        B        |L0.168|
|L0.134|
        ADDS     r3,r0,r1
        LDR      r4,|L0.788|
        STR      r3,[r4,#0]  ; ut_timer_5
        B        |L0.168|
|L0.142|
        ADDS     r3,r0,r1
        LDR      r4,|L0.792|
        STR      r3,[r4,#0]  ; ut_timer_6
        B        |L0.168|
|L0.150|
        ADDS     r3,r0,r1
        LDR      r4,|L0.796|
        STR      r3,[r4,#0]  ; ut_timer_7
        B        |L0.168|
|L0.158|
        ADDS     r3,r0,r1
        LDR      r4,|L0.800|
        STR      r3,[r4,#0]  ; ut_timer_8
        B        |L0.168|
|L0.166|
        NOP      
|L0.168|
        NOP      
        CMP      r2,#0
        BEQ      |L0.194|
        LDR      r3,|L0.804|
        LDR      r3,[r3,#0]  ; ut_set_flag
        ORRS     r3,r3,r2
        LDR      r4,|L0.804|
        STR      r3,[r4,#0]  ; ut_set_flag
        LDR      r3,|L0.808|
        LDR      r3,[r3,#0]  ; ut_expire_flag
        BICS     r3,r3,r2
        LDR      r4,|L0.808|
        STR      r3,[r4,#0]  ; ut_expire_flag
|L0.194|
        POP      {r4,pc}
        ENDP

UT_Get_Status PROC
        LDR      r0,|L0.804|
        LDR      r0,[r0,#0]  ; ut_set_flag
        BX       lr
        ENDP

UT_Clear_Timer PROC
        CMP      r0,#0x10
        BEQ      |L0.272|
        BGT      |L0.226|
        CMP      r0,#1
        BEQ      |L0.240|
        CMP      r0,#2
        BEQ      |L0.248|
        CMP      r0,#4
        BEQ      |L0.256|
        CMP      r0,#8
        BNE      |L0.304|
        B        |L0.264|
|L0.226|
        CMP      r0,#0x20
        BEQ      |L0.280|
        CMP      r0,#0x40
        BEQ      |L0.288|
        CMP      r0,#0x80
        BNE      |L0.304|
        B        |L0.296|
|L0.240|
        MOVS     r1,#0
        LDR      r2,|L0.772|
        STR      r1,[r2,#0]  ; ut_timer_1
        B        |L0.306|
|L0.248|
        MOVS     r1,#0
        LDR      r2,|L0.776|
        STR      r1,[r2,#0]  ; ut_timer_2
        B        |L0.306|
|L0.256|
        MOVS     r1,#0
        LDR      r2,|L0.780|
        STR      r1,[r2,#0]  ; ut_timer_3
        B        |L0.306|
|L0.264|
        MOVS     r1,#0
        LDR      r2,|L0.784|
        STR      r1,[r2,#0]  ; ut_timer_4
        B        |L0.306|
|L0.272|
        MOVS     r1,#0
        LDR      r2,|L0.788|
        STR      r1,[r2,#0]  ; ut_timer_5
        B        |L0.306|
|L0.280|
        MOVS     r1,#0
        LDR      r2,|L0.792|
        STR      r1,[r2,#0]  ; ut_timer_6
        B        |L0.306|
|L0.288|
        MOVS     r1,#0
        LDR      r2,|L0.796|
        STR      r1,[r2,#0]  ; ut_timer_7
        B        |L0.306|
|L0.296|
        MOVS     r1,#0
        LDR      r2,|L0.800|
        STR      r1,[r2,#0]  ; ut_timer_8
        B        |L0.306|
|L0.304|
        NOP      
|L0.306|
        NOP      
        CMP      r0,#0
        BEQ      |L0.332|
        LDR      r1,|L0.804|
        LDR      r1,[r1,#0]  ; ut_set_flag
        BICS     r1,r1,r0
        LDR      r2,|L0.804|
        STR      r1,[r2,#0]  ; ut_set_flag
        LDR      r1,|L0.808|
        LDR      r1,[r1,#0]  ; ut_expire_flag
        BICS     r1,r1,r0
        LDR      r2,|L0.808|
        STR      r1,[r2,#0]  ; ut_expire_flag
|L0.332|
        BX       lr
        ENDP

UT_Check_Expire PROC
        MOVS     r1,#0
        LDR      r2,|L0.812|
        LDR      r0,[r2,#0]  ; ut_tick
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        CMP      r2,#0
        BEQ      |L0.600|
        LDR      r2,|L0.804|
        LDRB     r2,[r2,#0]  ; ut_set_flag
        LSLS     r2,r2,#31
        LSRS     r2,r2,#31
        CMP      r2,#0
        BEQ      |L0.392|
        LDR      r2,|L0.772|
        LDR      r2,[r2,#0]  ; ut_timer_1
        CMP      r2,r0
        BHI      |L0.392|
        LDR      r2,|L0.772|
        LDR      r2,[r2,#0]  ; ut_timer_1
        SUBS     r2,r0,r2
        MOVS     r3,#1
        LSLS     r3,r3,#31
        CMP      r2,r3
        BCS      |L0.392|
        MOVS     r2,#0
        LDR      r3,|L0.772|
        STR      r2,[r3,#0]  ; ut_timer_1
        MOVS     r2,#1
        ORRS     r1,r1,r2
|L0.392|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#2
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.434|
        LDR      r2,|L0.776|
        LDR      r2,[r2,#0]  ; ut_timer_2
        CMP      r2,r0
        BHI      |L0.434|
        LDR      r2,|L0.776|
        LDR      r2,[r2,#0]  ; ut_timer_2
        SUBS     r2,r0,r2
        LSLS     r3,r3,#30
        CMP      r2,r3
        BCS      |L0.434|
        MOVS     r2,#0
        LDR      r3,|L0.776|
        STR      r2,[r3,#0]  ; ut_timer_2
        MOVS     r2,#2
        ORRS     r1,r1,r2
|L0.434|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#4
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.476|
        LDR      r2,|L0.780|
        LDR      r2,[r2,#0]  ; ut_timer_3
        CMP      r2,r0
        BHI      |L0.476|
        LDR      r2,|L0.780|
        LDR      r2,[r2,#0]  ; ut_timer_3
        SUBS     r2,r0,r2
        LSLS     r3,r3,#29
        CMP      r2,r3
        BCS      |L0.476|
        MOVS     r2,#0
        LDR      r3,|L0.780|
        STR      r2,[r3,#0]  ; ut_timer_3
        MOVS     r2,#4
        ORRS     r1,r1,r2
|L0.476|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#8
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.518|
        LDR      r2,|L0.784|
        LDR      r2,[r2,#0]  ; ut_timer_4
        CMP      r2,r0
        BHI      |L0.518|
        LDR      r2,|L0.784|
        LDR      r2,[r2,#0]  ; ut_timer_4
        SUBS     r2,r0,r2
        LSLS     r3,r3,#28
        CMP      r2,r3
        BCS      |L0.518|
        MOVS     r2,#0
        LDR      r3,|L0.784|
        STR      r2,[r3,#0]  ; ut_timer_4
        MOVS     r2,#8
        ORRS     r1,r1,r2
|L0.518|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#0x10
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.560|
        LDR      r2,|L0.788|
        LDR      r2,[r2,#0]  ; ut_timer_5
        CMP      r2,r0
        BHI      |L0.560|
        LDR      r2,|L0.788|
        LDR      r2,[r2,#0]  ; ut_timer_5
        SUBS     r2,r0,r2
        LSLS     r3,r3,#27
        CMP      r2,r3
        BCS      |L0.560|
        MOVS     r2,#0
        LDR      r3,|L0.788|
        STR      r2,[r3,#0]  ; ut_timer_5
        MOVS     r2,#0x10
        ORRS     r1,r1,r2
|L0.560|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#0x20
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.606|
        LDR      r2,|L0.792|
        LDR      r2,[r2,#0]  ; ut_timer_6
        CMP      r2,r0
        BHI      |L0.606|
        LDR      r2,|L0.792|
        LDR      r2,[r2,#0]  ; ut_timer_6
        SUBS     r2,r0,r2
        LSLS     r3,r3,#26
        CMP      r2,r3
        BCS      |L0.606|
        MOVS     r2,#0
        LDR      r3,|L0.792|
        STR      r2,[r3,#0]  ; ut_timer_6
        B        |L0.602|
|L0.600|
        B        |L0.704|
|L0.602|
        MOVS     r2,#0x20
        ORRS     r1,r1,r2
|L0.606|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#0x40
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.648|
        LDR      r2,|L0.796|
        LDR      r2,[r2,#0]  ; ut_timer_7
        CMP      r2,r0
        BHI      |L0.648|
        LDR      r2,|L0.796|
        LDR      r2,[r2,#0]  ; ut_timer_7
        SUBS     r2,r0,r2
        LSLS     r3,r3,#25
        CMP      r2,r3
        BCS      |L0.648|
        MOVS     r2,#0
        LDR      r3,|L0.796|
        STR      r2,[r3,#0]  ; ut_timer_7
        MOVS     r2,#0x40
        ORRS     r1,r1,r2
|L0.648|
        LDR      r2,|L0.804|
        LDR      r2,[r2,#0]  ; ut_set_flag
        MOVS     r3,#0x80
        ANDS     r2,r2,r3
        CMP      r2,#0
        BEQ      |L0.690|
        LDR      r2,|L0.800|
        LDR      r2,[r2,#0]  ; ut_timer_8
        CMP      r2,r0
        BHI      |L0.690|
        LDR      r2,|L0.800|
        LDR      r2,[r2,#0]  ; ut_timer_8
        SUBS     r2,r0,r2
        LSLS     r3,r3,#24
        CMP      r2,r3
        BCS      |L0.690|
        MOVS     r2,#0
        LDR      r3,|L0.800|
        STR      r2,[r3,#0]  ; ut_timer_8
        MOVS     r2,#0x80
        ORRS     r1,r1,r2
|L0.690|
        CMP      r1,#0
        BEQ      |L0.704|
        LDR      r2,|L0.808|
        LDR      r2,[r2,#0]  ; ut_expire_flag
        ORRS     r2,r2,r1
        LDR      r3,|L0.808|
        STR      r2,[r3,#0]  ; ut_expire_flag
|L0.704|
        BX       lr
        ENDP

UT_Is_Expired PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        BL       UT_Check_Expire
        MOVS     r5,#0
        LDR      r0,|L0.808|
        LDR      r0,[r0,#0]  ; ut_expire_flag
        CMP      r0,#0
        BEQ      |L0.766|
        CMP      r4,#0
        BEQ      |L0.766|
        LDR      r0,|L0.808|
        LDR      r0,[r0,#0]  ; ut_expire_flag
        ANDS     r0,r0,r4
        CMP      r0,r4
        BNE      |L0.766|
        MOVS     r5,#1
        LDR      r0,|L0.808|
        LDR      r0,[r0,#0]  ; ut_expire_flag
        BICS     r0,r0,r4
        LDR      r1,|L0.808|
        STR      r0,[r1,#0]  ; ut_expire_flag
        LDR      r0,|L0.804|
        LDR      r0,[r0,#0]  ; ut_set_flag
        BICS     r0,r0,r4
        LDR      r1,|L0.804|
        STR      r0,[r1,#0]  ; ut_set_flag
        MOV      r0,r4
        BL       UT_Clear_Timer
|L0.766|
        MOV      r0,r5
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L0.772|
        DCD      ut_timer_1
|L0.776|
        DCD      ut_timer_2
|L0.780|
        DCD      ut_timer_3
|L0.784|
        DCD      ut_timer_4
|L0.788|
        DCD      ut_timer_5
|L0.792|
        DCD      ut_timer_6
|L0.796|
        DCD      ut_timer_7
|L0.800|
        DCD      ut_timer_8
|L0.804|
        DCD      ut_set_flag
|L0.808|
        DCD      ut_expire_flag
|L0.812|
        DCD      ut_tick

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

ut_tick
        DCD      0x00000000
ut_set_flag
        DCD      0x00000000
ut_expire_flag
        DCD      0x00000000
ut_timer_1
        DCD      0x00000000
ut_timer_2
        DCD      0x00000000
ut_timer_3
        DCD      0x00000000
ut_timer_4
        DCD      0x00000000
ut_timer_5
        DCD      0x00000000
ut_timer_6
        DCD      0x00000000
ut_timer_7
        DCD      0x00000000
ut_timer_8
        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "..\\..\\code_lib\\user_timer.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___12_user_timer_c_ac03e58d____REV16|
#line 492 "..\\..\\..\\..\\..\\core\\cmsis\\include\\cmsis_armcc.h"
|__asm___12_user_timer_c_ac03e58d____REV16| PROC
#line 493

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___12_user_timer_c_ac03e58d____REVSH|
#line 507
|__asm___12_user_timer_c_ac03e58d____REVSH| PROC
#line 508

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT UT_Run_Timer [CODE]
        EXPORT SysTick_Handler [CODE]
        EXPORT UT_Set_Timer [CODE]
        EXPORT UT_Get_Status [CODE]
        EXPORT UT_Clear_Timer [CODE]
        EXPORT UT_Is_Expired [CODE]
        EXPORT ut_tick [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP UT_Check_Expire
        KEEP ut_set_flag
        KEEP ut_expire_flag
        KEEP ut_timer_1
        KEEP ut_timer_2
        KEEP ut_timer_3
        KEEP ut_timer_4
        KEEP ut_timer_5
        KEEP ut_timer_6
        KEEP ut_timer_7
        KEEP ut_timer_8

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
